{
  "hash": "5c56365af20b0a582774498019fa6e1b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 3, Session 4 — Survival ML (random survival forest, DeepSurv)\"\nsubtitle: \"Course 4 — Biostatistics Courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week3_session4_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Workflow labs** use the variant template:\nGoal → Approach → Execution → Check → Report.\n:::\n\n## Learning objectives\n\n- Fit a random survival forest and interpret its variable importance\n  and risk stratification.\n- Describe the DeepSurv architecture conceptually and when it is\n  preferred over the forest.\n- Compare against a Cox model on the same features.\n\n## Prerequisites\n\nCox regression and censoring from Course 2.\n\n## Background\n\nSurvival analysis deals with time-to-event data in the presence of\ncensoring. The Cox proportional-hazards model is the workhorse linear\nmethod; random survival forests (RSF) extend the idea of random\nforests to right-censored outcomes, using a log-rank split rule and\nHarrell's concordance as the default fit criterion. They handle\nnonlinearities and interactions automatically and are a good first\nnonparametric benchmark.\n\nDeepSurv is a neural-network generalisation of the Cox partial\nlikelihood: the linear predictor is replaced by a feed-forward\nnetwork. In small biomedical datasets it rarely beats a well-tuned RSF\nor a Cox model with splines, but the approach scales to large cohorts\nand to inputs where a representation must be learned.\n\n::: {.content-visible when-format=\"html\"}\nEvaluation of survival models uses time-integrated concordance\n(Harrell's C), the integrated Brier score, and — increasingly —\ndecision curves at a clinically relevant horizon. Reporting only C on\na single test set is weak evidence.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\nlibrary(randomForestSRC)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Goal\n\nFit an RSF on `survival::pbc` and compare to a Cox model using\nHarrell's concordance.\n\n## 2. Approach\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- survival::pbc |>\n  as_tibble() |>\n  drop_na(bili, albumin, age, edema, protime, stage) |>\n  mutate(status = ifelse(status == 2, 1, 0))\n\nggplot(d, aes(time / 365.25, fill = factor(status))) +\n  geom_histogram(bins = 30, alpha = 0.7, position = \"identity\") +\n  labs(x = \"follow-up (years)\", y = \"count\", fill = \"event\")\n```\n\n::: {.cell-output-display}\n![](lab_week3_session4_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## 3. Execution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_cox <- coxph(Surv(time, status) ~ bili + albumin + age + edema +\n                   protime + stage, data = d)\nfit_rsf <- rfsrc(Surv(time, status) ~ bili + albumin + age + edema +\n                   protime + stage,\n                 data = as.data.frame(d), ntree = 500,\n                 importance = TRUE)\nfit_rsf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         Sample size: 410\n                    Number of deaths: 156\n                     Number of trees: 500\n           Forest terminal node size: 15\n       Average no. of terminal nodes: 19.574\nNo. of variables tried at each split: 3\n              Total no. of variables: 6\n       Resampling used to grow trees: swor\n    Resample size used to grow trees: 259\n                            Analysis: RSF\n                              Family: surv\n                      Splitting rule: logrank *random*\n       Number of random split points: 10\n                          (OOB) CRPS: 505.07481851\n             (OOB) standardized CRPS: 0.12051415\n   (OOB) Requested performance error: 0.18039411\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(var = names(fit_rsf$importance),\n       imp = as.numeric(fit_rsf$importance)) |>\n  arrange(desc(imp)) |>\n  ggplot(aes(reorder(var, imp), imp)) +\n  geom_col() + coord_flip() + labs(x = NULL, y = \"VIMP\")\n```\n\n::: {.cell-output-display}\n![](lab_week3_session4_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## 4. Check\n\nCompare concordance on held-out data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nidx <- sample(nrow(d), 0.7 * nrow(d))\ntr <- d[idx, ]; te <- d[-idx, ]\ncox2 <- coxph(Surv(time, status) ~ bili + albumin + age + edema +\n                protime + stage, data = tr)\nrsf2 <- rfsrc(Surv(time, status) ~ bili + albumin + age + edema +\n                protime + stage,\n              data = as.data.frame(tr), ntree = 500)\nc_cox <- survival::concordance(cox2, newdata = te)$concordance\np_rsf <- predict(rsf2, newdata = as.data.frame(te))$predicted\nc_rsf <- survival::concordance(Surv(te$time, te$status) ~ p_rsf,\n                               reverse = TRUE)$concordance\nc(cox = c_cox, rsf = c_rsf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      cox       rsf \n0.7854077 0.8071531 \n```\n\n\n:::\n:::\n\n\nDeepSurv conceptual sketch.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(torch)\n# A DeepSurv-style loss computes the partial log-likelihood on the\n# sorted risk set. The network output h(x) replaces the Cox linear\n# predictor; the loss is  -(sum_{i:event}  h(x_i) - log sum_{j in R_i} exp(h(x_j))).\ndeepsurv_loss <- function(risk, time, event) {\n  ord <- order(time, decreasing = TRUE)\n  risk <- risk[ord]; event <- event[ord]\n  log_cumsum <- torch_logcumsumexp(risk, dim = 1)\n  -torch_sum(event * (risk - log_cumsum)) / torch_sum(event)\n}\n```\n:::\n\n\n## 5. Report\n\n> On `survival::pbc`, a random survival forest achieved test\n> concordance 0.807 compared with\n> 0.785 for a multivariable Cox model. Bilirubin,\n> albumin, and age dominated VIMP. A DeepSurv network with the\n> partial-likelihood loss would be the natural next step on a larger\n> cohort.\n\nOn this sample size, the RSF and Cox model are close; on larger\ndatasets with nonlinearities, the forest often pulls ahead.\n\n::: {.notes}\nMention that `randomForestSRC::vimp` has a permutation variant worth\npreferring for correlated predictors.\n:::\n\n## Common pitfalls\n\n- Treating the Cox proportional-hazards assumption as always met; it\n  often is not, and the RSF is more robust to violation.\n- Comparing models without the same censoring distribution in the\n  test set.\n- Reporting only C without a calibration or decision curve at the\n  horizon of interest.\n\n## Further reading\n\n- Ishwaran H et al. (2008), *Random survival forests*.\n- Katzman JL et al. (2018), *DeepSurv: Personalized treatment\n  recommender system using a Cox proportional hazards deep neural\n  network*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] randomForestSRC_3.6.2 survival_3.8-6        lubridate_1.9.5      \n [4] forcats_1.0.1         stringr_1.6.0         dplyr_1.2.0          \n [7] purrr_1.2.2           readr_2.2.0           tidyr_1.3.2          \n[10] tibble_3.3.1          ggplot2_4.0.3         tidyverse_2.0.0      \n\nloaded via a namespace (and not attached):\n [1] Matrix_1.7-5       gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2    \n [5] tidyselect_1.2.1   parallel_4.5.2     DiagrammeR_1.0.12  splines_4.5.2     \n [9] scales_1.4.0       yaml_2.3.12        fastmap_1.2.0      lattice_0.22-9    \n[13] R6_2.6.1           labeling_0.4.3     generics_0.1.4     knitr_1.51        \n[17] visNetwork_2.1.4   htmlwidgets_1.6.4  pillar_1.11.1      RColorBrewer_1.1-3\n[21] tzdb_0.5.0         rlang_1.2.0        stringi_1.8.7      xfun_0.57         \n[25] S7_0.2.2           otel_0.2.0         timechange_0.4.0   cli_3.6.6         \n[29] withr_3.0.2        magrittr_2.0.4     digest_0.6.39      grid_4.5.2        \n[33] hms_1.1.4          data.tree_1.2.0    lifecycle_1.0.5    vctrs_0.7.3       \n[37] evaluate_1.0.5     glue_1.8.0         farver_2.1.2       rmarkdown_2.31    \n[41] tools_4.5.2        pkgconfig_2.0.3    htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n\n::: {.vgwort-pixel}\n```{=html}\n<!-- VG Wort Zählmarke — public ID: 11b9d1ecccdd43fa82b36029deb72696 -->\n<img src=\"https://vg09.met.vgwort.de/na/11b9d1ecccdd43fa82b36029deb72696\"\n     width=\"1\" height=\"1\" alt=\"\"\n     loading=\"eager\"\n     fetchpriority=\"high\"\n     decoding=\"async\"\n     style=\"position:absolute;visibility:hidden;\" />\n```\n:::\n",
    "supporting": [
      "lab_week3_session4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}