{
  "hash": "4380753f5b1c6ff7100869f803e2ce93",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 1, Session 1 — Cross-validation, nested CV, bootstrap .632+\"\nsubtitle: \"Course 4 — Biostatistics Courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week1_session1_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Workflow labs** use the variant template:\nGoal → Approach → Execution → Check → Report.\n:::\n\n## Learning objectives\n\n- Implement k-fold and repeated k-fold cross-validation from scratch and\n  with a package, and report an honest generalisation error.\n- Explain why selecting a model *and* tuning a hyperparameter on the same\n  fold inflates performance, and use nested CV to fix it.\n- Compute a bootstrap .632+ estimate and say when it is preferable to\n  CV.\n\n## Prerequisites\n\nCourse 1 material on sampling variability; comfort with `caret` or\nbase-R model fitting.\n\n## Background\n\nEvery predictive model reports an error on the data it was fit to. That\nnumber is almost always optimistic, because the fit has had a chance to\nmemorise noise as well as signal. Cross-validation and the bootstrap are\ntwo resampling strategies that simulate the experience of scoring the\nmodel on data it has not seen. They are not interchangeable: they make\ndifferent trade-offs between bias and variance, and they behave\ndifferently under high-dimensional settings.\n\nA particular failure mode that recurs in the applied literature is\n*double dipping*: using the same held-out fold both to choose a\nhyperparameter and to report the final error. The fold is then no longer\nheld out, and the reported error slides back toward the training error.\nNested cross-validation is the clean solution: the inner loop picks\nhyperparameters, the outer loop reports error.\n\nThe bootstrap gives a different window onto generalisation. The plain\nbootstrap resamples with replacement; the .632 and .632+ variants\nweight the in-bag and out-of-bag errors to reduce bias when the learner\noverfits. In very small samples the .632+ estimator is often the most\nstable, and it is worth carrying in your toolbox alongside CV.\n\n::: {.content-visible when-format=\"html\"}\nA practical note: when you write up a modelling study, the\ngeneralisation error is the headline number. If you tuned, you must\ndisclose how. If the inner tuning cost was hidden in the outer fold, a\ncareful reader will notice that the reported error is too good and\ncannot be reproduced. Nested CV is not a cosmetic fix; it is the\ndifference between a number that generalises and a number that does\nnot.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(glmnet)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Goal\n\nEstimate the generalisation error of a lasso on a moderate *p*, small\n*n* simulated regression problem, first naively, then with a proper\nnested cross-validation.\n\n## 2. Approach\n\nWe simulate `n = 120` observations with `p = 40` features, of which\nonly 5 are true signal. We will (i) fit a single `cv.glmnet`, (ii)\nreport the CV-minimising error, then (iii) wrap that in an outer 5-fold\nloop to show that the inner CV error is optimistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 120; p <- 40\nX <- matrix(rnorm(n * p), n, p)\nbeta <- c(rep(1.5, 5), rep(0, p - 5))\ny <- as.numeric(X %*% beta + rnorm(n, sd = 1.0))\n\ntibble(yhat_naive = as.numeric(X %*% beta), y = y) |>\n  ggplot(aes(yhat_naive, y)) +\n  geom_point(alpha = 0.6) +\n  geom_abline(slope = 1, intercept = 0, colour = \"grey50\") +\n  labs(x = \"True linear predictor\", y = \"Observed y\")\n```\n\n::: {.cell-output-display}\n![](lab_week1_session1_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## 3. Execution\n\n**Naive single-layer CV.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncv1 <- cv.glmnet(X, y, alpha = 1, nfolds = 5)\nnaive_mse <- min(cv1$cvm)\nnaive_mse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.206876\n```\n\n\n:::\n:::\n\n\n**Nested CV.** The inner `cv.glmnet` picks `lambda`; the outer 5 folds\nproduce the reported MSE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nK <- 5\nfolds <- sample(rep(1:K, length.out = n))\nouter_mse <- numeric(K)\nfor (k in 1:K) {\n  tr <- folds != k; te <- folds == k\n  fit_k <- cv.glmnet(X[tr, ], y[tr], alpha = 1, nfolds = 5)\n  yhat  <- as.numeric(predict(fit_k, newx = X[te, ], s = \"lambda.min\"))\n  outer_mse[k] <- mean((y[te] - yhat)^2)\n}\nnested_mse <- mean(outer_mse)\nc(naive = naive_mse, nested = nested_mse)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   naive   nested \n1.206876 1.048175 \n```\n\n\n:::\n:::\n\n\n## 4. Check\n\nBootstrap .632+ error as a cross-check.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB <- 50\nerrs_in <- errs_oob <- numeric(B)\nfor (b in 1:B) {\n  idx <- sample.int(n, n, replace = TRUE)\n  oob <- setdiff(seq_len(n), unique(idx))\n  fit_b <- cv.glmnet(X[idx, ], y[idx], alpha = 1, nfolds = 5)\n  yhat_in  <- as.numeric(predict(fit_b, newx = X[idx, ],  s = \"lambda.min\"))\n  yhat_oob <- as.numeric(predict(fit_b, newx = X[oob, ],  s = \"lambda.min\"))\n  errs_in[b]  <- mean((y[idx] - yhat_in)^2)\n  errs_oob[b] <- mean((y[oob] - yhat_oob)^2)\n}\nerr_app <- mean(errs_in); err_oob <- mean(errs_oob)\nerr_632 <- 0.368 * err_app + 0.632 * err_oob\nc(apparent = err_app, oob = err_oob, boot632 = err_632,\n  nested = nested_mse)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n apparent       oob   boot632    nested \n0.5199837 1.2632623 0.9897358 1.0481752 \n```\n\n\n:::\n:::\n\n\n## 5. Report\n\n> On simulated data (*n* = 120, *p* = 40, five true signals), a lasso\n> with tuning parameter chosen by 5-fold CV achieved an out-of-sample\n> MSE of 1.05 under nested 5 × 5 CV. The naive\n> single-layer CV understated the error at\n> 1.21; the bootstrap .632 estimator gave\n> 0.99, which bracketed the nested estimate.\n\nThe naive number looks tighter, but it reflects the choice of `lambda`\nas well as the fit. Only the nested number is a fair estimate of what\nthis procedure — tune-then-fit — will do on new data.\n\n::: {.notes}\nEmphasise that \"naive CV\" is still useful: it is the inner loop in a\nnested scheme. The crime is reporting it as the final error.\n:::\n\n## Common pitfalls\n\n- Tuning on the test fold and reporting the resulting error.\n- Using a single 80/20 split in high dimensions; variance across splits\n  can exceed the effect of interest.\n- Bootstrapping without tracking in-bag vs out-of-bag, which inflates\n  the estimate back to the apparent error.\n\n## Further reading\n\n- Hastie, Tibshirani, Friedman, *Elements of Statistical Learning*,\n  §7.10–7.11.\n- Varma S, Simon R (2006), *Bias in error estimation when using\n  cross-validation for model selection*.\n- Efron B, Tibshirani R (1997), *Improvements on cross-validation: the\n  .632+ bootstrap method*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] glmnet_5.0      Matrix_1.7-5    lubridate_1.9.5 forcats_1.0.1  \n [5] stringr_1.6.0   dplyr_1.2.0     purrr_1.2.2     readr_2.2.0    \n [9] tidyr_1.3.2     tibble_3.3.1    ggplot2_4.0.3   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] generics_0.1.4     shape_1.4.6.1      stringi_1.8.7      lattice_0.22-9    \n [5] hms_1.1.4          digest_0.6.39      magrittr_2.0.4     evaluate_1.0.5    \n [9] grid_4.5.2         timechange_0.4.0   RColorBrewer_1.1-3 iterators_1.0.14  \n[13] fastmap_1.2.0      foreach_1.5.2      jsonlite_2.0.0     survival_3.8-6    \n[17] scales_1.4.0       codetools_0.2-20   cli_3.6.5          rlang_1.2.0       \n[21] splines_4.5.2      withr_3.0.2        yaml_2.3.12        otel_0.2.0        \n[25] tools_4.5.2        tzdb_0.5.0         vctrs_0.7.3        R6_2.6.1          \n[29] lifecycle_1.0.5    htmlwidgets_1.6.4  pkgconfig_2.0.3    pillar_1.11.1     \n[33] gtable_0.3.6       glue_1.8.0         Rcpp_1.1.1-1.1     xfun_0.57         \n[37] tidyselect_1.2.1   knitr_1.51         farver_2.1.2       htmltools_0.5.9   \n[41] rmarkdown_2.31     labeling_0.4.3     compiler_4.5.2     S7_0.2.2          \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week1_session1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}