{
  "hash": "60bc60145291081853ee08d2862d9afc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 1, Session 1 — Observational designs and STROBE\"\nsubtitle: \"Course 3 — #courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week1_session1_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Workflow lab** using the variant template:\nGoal → Approach → Execution → Check → Report.\n:::\n\n## Learning objectives\n\n- Distinguish cohort, case-control, and cross-sectional designs and\n  say when each is the right tool.\n- Simulate a source population and draw both a cohort sample and a\n  nested case-control sample from it.\n- Map a study report to the STROBE checklist.\n\n## Prerequisites\n\nCourse 1 (inference) and Course 2 (regression). Familiarity with\ntibbles and `glm()`.\n\n## Background\n\nObservational designs differ primarily in how participants enter the\nstudy and when the outcome is measured relative to the exposure. In a\ncohort we sample on exposure and wait; in a case-control we sample on\nthe outcome and look back; in a cross-sectional we sample once and\nmeasure everything together. The choice is driven by how common the\noutcome is, how long it takes to develop, and how easy the exposure\nis to measure retrospectively.\n\nSTROBE (Strengthening the Reporting of Observational Studies in\nEpidemiology) is the reporting checklist that keeps observational\npapers honest. It has 22 items covering title and abstract,\nintroduction, methods, results, and discussion, with specific\nbranches for the three main designs. You do not need to memorise it;\nyou need to know that reviewers will check it.\n\n::: {.content-visible when-format=\"html\"}\nA nested case-control sampled from a defined cohort behaves\nstatistically like the full cohort for odds ratios that approximate\nrisk ratios when the outcome is rare. This is the trick behind most\nlarge pharmacoepidemiology studies: a full-cohort analysis is\nwasteful when measurement on every unexposed person is expensive, so\nanalysts sample controls from the risk set instead.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Goal\n\nSimulate a source population, carve a cohort study and a nested\ncase-control study out of it, and compare the exposure–outcome\nassociation recovered by each.\n\n## 2. Approach\n\nWe generate a population of 5000 people with a binary exposure and a\nbinary outcome whose probability depends on exposure and a confounder\n(age). We then (a) analyse the full cohort and (b) draw a\ncase-control sample with four controls per case.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_pop <- 5000\npop <- tibble(\n  id       = seq_len(n_pop),\n  age      = rnorm(n_pop, 55, 10),\n  exposure = rbinom(n_pop, 1, 0.30)\n)\n# outcome depends on exposure (log OR ~ 0.8) and age\nlp <- -4 + 0.8 * pop$exposure + 0.04 * (pop$age - 55)\npop <- pop |>\n  mutate(prob = plogis(lp),\n         outcome = rbinom(n_pop, 1, prob))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npop |>\n  count(exposure, outcome) |>\n  mutate(exposure = factor(exposure, labels = c(\"unexposed\", \"exposed\")),\n         outcome  = factor(outcome,  labels = c(\"no\", \"yes\"))) |>\n  ggplot(aes(exposure, n, fill = outcome)) +\n  geom_col(position = \"dodge\", alpha = 0.8) +\n  labs(x = NULL, y = \"Count\", fill = \"Outcome\")\n```\n\n::: {.cell-output-display}\n![](lab_week1_session1_files/figure-html/unnamed-chunk-2-1.png){width=576}\n:::\n:::\n\n\n## 3. Execution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cohort analysis on full population\nfit_cohort <- glm(outcome ~ exposure + age, data = pop, family = binomial)\ncoef_cohort <- broom::tidy(fit_cohort, conf.int = TRUE, exponentiate = TRUE)\ncoef_cohort\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)  0.00361   0.512      -11.0  4.75e-28  0.00130   0.00972\n2 exposure     1.92      0.174        3.75 1.74e- 4  1.36      2.71   \n3 age          1.03      0.00863      3.74 1.87e- 4  1.02      1.05   \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Nested case-control: all cases, 4 controls per case\ncases    <- pop |> filter(outcome == 1)\ncontrols <- pop |>\n  filter(outcome == 0) |>\n  slice_sample(n = 4 * nrow(cases))\nncc <- bind_rows(cases, controls)\nfit_ncc <- glm(outcome ~ exposure + age, data = ncc, family = binomial)\ncoef_ncc <- broom::tidy(fit_ncc, conf.int = TRUE, exponentiate = TRUE)\ncoef_ncc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term        estimate std.error statistic       p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>         <dbl>    <dbl>     <dbl>\n1 (Intercept)   0.0347   0.565       -5.95 0.00000000263   0.0112     0.103\n2 exposure      2.10     0.197        3.76 0.000168        1.43       3.09 \n3 age           1.03     0.00954      3.16 0.00156         1.01       1.05 \n```\n\n\n:::\n:::\n\n\n## 4. Check\n\nThe exposure odds ratio from the nested case-control should be close\nto that from the cohort, because the outcome is uncommon. Precision\nis worse in the case-control sample but the point estimate is not\nbiased by the sampling scheme.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  cohort = coef_cohort |> filter(term == \"exposure\"),\n  ncc    = coef_ncc    |> filter(term == \"exposure\"),\n  .id = \"design\"\n) |>\n  select(design, estimate, conf.low, conf.high)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  design estimate conf.low conf.high\n  <chr>     <dbl>    <dbl>     <dbl>\n1 cohort     1.92     1.36      2.71\n2 ncc        2.10     1.43      3.09\n```\n\n\n:::\n:::\n\n\n## 5. Report\n\n> In a simulated source population of 5000 adults, exposure was\n> associated with the outcome with an adjusted odds ratio of\n> 1.92 (95% CI:\n> 1.36 to\n> 2.71) in a full-cohort analysis,\n> and 2.1 (95% CI:\n> 1.43 to\n> 3.09) in a 1:4 nested case-control\n> sample.\n\n### STROBE in one paragraph\n\nReport the sampling frame, the eligibility criteria, the exposure and\noutcome definitions, how confounders were chosen and handled,\nwhatever you did about missing data, and a flow diagram of who was\nincluded, excluded, and lost. If you can do those six things clearly,\nyou have answered most of the STROBE items for free.\n\n::: {.notes}\nThe point of this lab is that the design choice is not about the\nmodel — it is about who gets measured. Reinforce that during the\nslides.\n:::\n\n## Common pitfalls\n\n- Treating a cross-sectional association as evidence of a causal\n  effect when temporality is unknown.\n- Reporting an odds ratio as a risk ratio when the outcome is\n  common.\n- Drawing controls from a different population than the cases.\n- Skipping a flow diagram in an observational paper.\n\n## Further reading\n\n- von Elm E et al. (2007), *The STROBE Statement*.\n- Rothman KJ, Greenland S, Lash TL. *Modern Epidemiology*, ch. 6–8.\n- Pearce N (2016), *Analysis of matched case-control studies*, BMJ.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.5 forcats_1.0.1   stringr_1.6.0   dplyr_1.2.1    \n [5] purrr_1.2.2     readr_2.2.0     tidyr_1.3.2     tibble_3.3.1   \n [9] ggplot2_4.0.3   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2     tidyselect_1.2.1  \n [5] scales_1.4.0       yaml_2.3.12        fastmap_1.2.0      R6_2.6.1          \n [9] labeling_0.4.3     generics_0.1.4     knitr_1.51         backports_1.5.1   \n[13] htmlwidgets_1.6.4  pillar_1.11.1      RColorBrewer_1.1-3 tzdb_0.5.0        \n[17] rlang_1.2.0        utf8_1.2.6         broom_1.0.12       stringi_1.8.7     \n[21] xfun_0.57          S7_0.2.2           otel_0.2.0         timechange_0.4.0  \n[25] cli_3.6.6          withr_3.0.2        magrittr_2.0.4     digest_0.6.39     \n[29] grid_4.5.2         hms_1.1.4          lifecycle_1.0.5    vctrs_0.7.3       \n[33] evaluate_1.0.5     glue_1.8.1         farver_2.1.2       rmarkdown_2.31    \n[37] tools_4.5.2        pkgconfig_2.0.3    htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week1_session1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}