{
  "hash": "d00d90360ca05bdf78a8d6680f201fb7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 2, Session 3 — RCBD and repeated measures → mixed models\"\nsubtitle: \"Course 2 — #courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week2_session3_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Inference labs** use the five-step template:\nHypothesis → Visualise → Assumptions → Conduct → Conclude.\n:::\n\n## Learning objectives\n\n- Fit a randomised complete block design (RCBD) with `aov()` and read\n  the block term.\n- Move from repeated-measures ANOVA to a mixed model with\n  `lme4::lmer()`.\n- Interpret random intercepts as between-subject variance and residuals\n  as within-subject variance.\n\n## Prerequisites\n\nSessions 1–2 of this week.\n\n## Background\n\nBlocks and repeated measures share a single idea: some units are more\nsimilar to themselves than to the rest of the data. In an RCBD, the\nblock absorbs nuisance variation (plots in a field, litter in an\nexperiment) so the treatment effect can be estimated against a smaller\nerror. In repeated-measures designs, subjects serve as their own\nblocks because each is measured more than once. In both cases,\nignoring the grouping inflates the standard error of the treatment\neffect and sometimes the Type I error of the test.\n\nClassical RCBD ANOVA treats the block as a fixed factor with a line in\nthe ANOVA table. Modern practice is usually to treat the block (or\nsubject) as a random effect in a mixed model, which separates\nbetween-block and within-block variance explicitly and produces\nstandard errors that account for the correlation.\n\n::: {.content-visible when-format=\"html\"}\nThe `sleep` dataset from base R is a ready-made within-subject design:\neach of ten subjects received two drugs and reported extra hours of\nsleep. A paired *t*-test answers the main question; a mixed model\nwith subject as a random intercept is the same thing with more\nmachinery and more honest diagnostics.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(broom.mixed)\nlibrary(lme4)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Hypothesis\n\nUsing the `sleep` dataset, does drug group affect extra hours of sleep\nafter accounting for the within-subject pairing?\n\n## 2. Visualise\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sleep, aes(group, extra, group = ID)) +\n  geom_line(colour = \"grey70\") +\n  geom_point(aes(colour = group), size = 3) +\n  labs(x = \"Drug\", y = \"Extra sleep (hours)\", colour = \"Drug\")\n```\n\n::: {.cell-output-display}\n![](lab_week2_session3_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nLines track each subject across the two drugs. Most rise from left to\nright, suggesting drug 2 adds more sleep than drug 1.\n\n## 3. Assumptions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_rcbd <- aov(extra ~ group + Error(ID), data = sleep)\nsummary(fit_rcbd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nError: ID\n          Df Sum Sq Mean Sq F value Pr(>F)\nResiduals  9  58.08   6.453               \n\nError: Within\n          Df Sum Sq Mean Sq F value  Pr(>F)   \ngroup      1 12.482  12.482    16.5 0.00283 **\nResiduals  9  6.808   0.756                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nResidual diagnostics for the mixed version:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lmm <- lmer(extra ~ group + (1 | ID), data = sleep)\nqqnorm(resid(fit_lmm)); qqline(resid(fit_lmm))\n```\n\n::: {.cell-output-display}\n![](lab_week2_session3_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(fitted(fit_lmm), resid(fit_lmm),\n     xlab = \"Fitted\", ylab = \"Residuals\"); abline(h = 0, lty = 2)\n```\n\n::: {.cell-output-display}\n![](lab_week2_session3_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n:::\n\n\n## 4. Conduct\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_lmm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: extra ~ group + (1 | ID)\n   Data: sleep\n\nREML criterion at convergence: 70\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.63372 -0.34157  0.03346  0.31511  1.83859 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n ID       (Intercept) 2.8483   1.6877  \n Residual             0.7564   0.8697  \nNumber of obs: 20, groups:  ID, 10\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept)   0.7500     0.6004   1.249\ngroup2        1.5800     0.3890   4.062\n\nCorrelation of Fixed Effects:\n       (Intr)\ngroup2 -0.324\n```\n\n\n:::\n\n```{.r .cell-code}\ntidy(fit_lmm, conf.int = TRUE, effects = \"fixed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  effect term        estimate std.error statistic conf.low conf.high\n  <chr>  <chr>          <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n1 fixed  (Intercept)    0.750     0.600      1.25   -0.427      1.93\n2 fixed  group2         1.58      0.389      4.06    0.818      2.34\n```\n\n\n:::\n:::\n\n\nThe random intercept variance captures between-subject differences in\nbaseline sleep; the residual variance captures within-subject noise.\n\n## 5. Concluding statement\n\n> In ten subjects each given both drugs, drug 2 was associated with\n> 1.58 additional hours of extra sleep\n> relative to drug 1 (95% CI from the mixed model:\n> 0.82 to\n> 2.34). The model\n> included a random intercept for subject to account for the pairing.\n\n::: {.notes}\nPoint out that the paired *t*-test, RCBD ANOVA, and mixed model all\nagree here; the mixed model is useful because it extends cleanly to\nunbalanced designs and longitudinal data.\n:::\n\n## Common pitfalls\n\n- Ignoring the pairing and fitting a two-sample *t*-test.\n- Fitting a random slope that the data cannot identify (tiny cluster\n  sizes).\n- Reporting only fixed-effect estimates and omitting the variance\n  components.\n\n## Further reading\n\n- Pinheiro JC, Bates DM. *Mixed-Effects Models in S and S-PLUS*.\n- Bates D et al. (2015), *Fitting linear mixed-effects models using lme4*.\n- Zuur AF et al. *Mixed Effects Models and Extensions in Ecology*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lme4_2.0-1          Matrix_1.7-5        broom.mixed_0.2.9.7\n [4] broom_1.0.12        lubridate_1.9.5     forcats_1.0.1      \n [7] stringr_1.6.0       dplyr_1.2.1         purrr_1.2.2        \n[10] readr_2.2.0         tidyr_1.3.2         tibble_3.3.1       \n[13] ggplot2_4.0.3       tidyverse_2.0.0    \n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       xfun_0.57          htmlwidgets_1.6.4  lattice_0.22-9    \n [5] tzdb_0.5.0         vctrs_0.7.3        tools_4.5.2        Rdpack_2.6.6      \n [9] generics_0.1.4     parallel_4.5.2     pkgconfig_2.0.3    RColorBrewer_1.1-3\n[13] S7_0.2.2           lifecycle_1.0.5    compiler_4.5.2     farver_2.1.2      \n[17] codetools_0.2-20   htmltools_0.5.9    yaml_2.3.12        pillar_1.11.1     \n[21] furrr_0.4.0        nloptr_2.2.1       MASS_7.3-65        reformulas_0.4.4  \n[25] boot_1.3-32        nlme_3.1-169       parallelly_1.47.0  tidyselect_1.2.1  \n[29] digest_0.6.39      stringi_1.8.7      future_1.70.0      listenv_0.10.1    \n[33] labeling_0.4.3     splines_4.5.2      fastmap_1.2.0      grid_4.5.2        \n[37] cli_3.6.6          magrittr_2.0.4     utf8_1.2.6         withr_3.0.2       \n[41] scales_1.4.0       backports_1.5.1    timechange_0.4.0   rmarkdown_2.31    \n[45] globals_0.19.1     otel_0.2.0         hms_1.1.4          evaluate_1.0.5    \n[49] knitr_1.51         rbibutils_2.4.1    rlang_1.2.0        Rcpp_1.1.1-1.1    \n[53] glue_1.8.1         minqa_1.2.8        jsonlite_2.0.0     R6_2.6.1          \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week2_session3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}