{
  "hash": "b1cde749744c28e943a85c9891060fae",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 3, Session 4 — Propensity scores and IPTW\"\nsubtitle: \"Course 3 — Biostatistics Courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week3_session4_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Inference lab** using the five-step template:\nHypothesis → Visualise → Assumptions → Conduct → Conclude.\n:::\n\n## Learning objectives\n\n- Estimate a propensity score and match nearest-neighbour with\n  `MatchIt`.\n- Construct inverse-probability-of-treatment weights (IPTW) and fit\n  a weighted outcome model.\n- Diagnose covariate balance with `cobalt::love.plot`.\n\n## Prerequisites\n\nSession 3 (DAGs). Course 2 logistic regression.\n\n## Background\n\nThe propensity score is the probability of being treated given\ncovariates. Under the assumptions of conditional exchangeability\nand positivity, conditioning on the propensity score yields an\nunbiased estimate of the average treatment effect. Matching and\ninverse-probability-of-treatment weighting are two ways to do that\nconditioning.\n\nMatching pairs each treated unit with one (or more) untreated units\nwith similar propensity scores, then analyses the matched sample.\nIPTW gives each unit a weight of 1/e(X) if treated and 1/(1 − e(X))\nif untreated, creating a pseudo-population where treatment is\nindependent of X. Both estimators require the propensity model to\nbe correctly specified; neither handles unmeasured confounding.\n\nBalance diagnostics assess whether the matched or weighted sample\nhas covariate distributions that are similar across treatment\ngroups. The standardised mean difference (SMD) is the workhorse\nmetric; anything below 0.1 is usually considered balanced.\n\n::: {.content-visible when-format=\"html\"}\nLarge weights (extreme propensities near 0 or 1) are a sign of\npoor positivity. Stabilised weights and truncation can help, but\nthe underlying problem — a region of covariate space where one\ntreatment is never seen — cannot be fixed statistically.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(MatchIt)\nlibrary(cobalt)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Hypothesis\n\nTreatment reduces the outcome by a known amount. We will estimate\nthe effect with naive regression, matching, and IPTW, and compare\nwith the simulated truth.\n\n## 2. Visualise\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 1000\ndat <- tibble(\n  age  = rnorm(n, 60, 10),\n  sev  = rnorm(n, 0,   1),\n  sex  = rbinom(n, 1, 0.5)\n) |>\n  mutate(ps = plogis(-1 + 0.04 * (age - 60) + 0.8 * sev + 0.3 * sex),\n         trt = rbinom(n, 1, ps),\n         y   = 2 - 1.5 * trt + 0.05 * (age - 60) +\n                 0.8 * sev + 0.3 * sex + rnorm(n, 0, 1))\n\nggplot(dat, aes(ps, fill = factor(trt))) +\n  geom_density(alpha = 0.5) +\n  labs(x = \"Propensity score\", y = \"Density\", fill = \"Treated?\")\n```\n\n::: {.cell-output-display}\n![](lab_week3_session4_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## 3. Assumptions\n\nNo unmeasured confounding (conditional exchangeability); positivity\n(everyone has a non-zero chance of each treatment); correct\nspecification of the propensity model.\n\n## 4. Conduct\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Naive regression\nfit_naive <- lm(y ~ trt + age + sev + sex, data = dat)\ncoef(fit_naive)[\"trt\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      trt \n-1.502417 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Nearest-neighbour matching\nm <- matchit(trt ~ age + sev + sex, data = dat,\n             method = \"nearest\", ratio = 1)\nm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA `matchit` object\n - method: 1:1 nearest neighbor matching without replacement\n - distance: Propensity score\n             - estimated with logistic regression\n - number of obs.: 1000 (original), 688 (matched)\n - target estimand: ATT\n - covariates: age, sev, sex\n```\n\n\n:::\n\n```{.r .cell-code}\nmatched <- match.data(m)\n\nfit_match <- lm(y ~ trt, data = matched,\n                weights = matched$weights)\ncoef(fit_match)[\"trt\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      trt \n-1.281375 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# IPTW\ndat <- dat |>\n  mutate(w = if_else(trt == 1, 1 / ps, 1 / (1 - ps)))\nfit_iptw <- lm(y ~ trt, data = dat, weights = w)\ncoef(fit_iptw)[\"trt\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      trt \n-1.592614 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlove.plot(m, thresholds = c(m = 0.1), abs = TRUE)\n```\n\n::: {.cell-output-display}\n![](lab_week3_session4_files/figure-html/unnamed-chunk-5-1.png){width=576}\n:::\n:::\n\n\n## 5. Concluding statement\n\n> The simulated treatment effect was −1.5. The naive regression\n> gave -1.5; nearest-neighbour\n> matching gave -1.28; IPTW gave\n> -1.59. Balance plots showed that\n> matching reduced all SMDs below 0.1.\n\n::: {.notes}\nMake sure students understand that a well-balanced sample is a\nnecessary but not sufficient condition for an unbiased effect\nestimate.\n:::\n\n## Common pitfalls\n\n- Matching with replacement without adjusting inference for the\n  repeated use of controls.\n- Reporting only the *p*-value for the treatment effect in the\n  weighted model without a sandwich or bootstrap standard error.\n- Ignoring extreme weights.\n- Picking the matching method that gives the effect you wanted.\n\n## Further reading\n\n- Austin PC (2011), *An introduction to propensity score methods\n  for reducing the effects of confounding in observational\n  studies*.\n- Stuart EA (2010), *Matching methods for causal inference*.\n- Hernán MA, Robins JM. *Causal Inference: What If*, ch. 12.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] cobalt_4.6.2    MatchIt_4.7.2   lubridate_1.9.5 forcats_1.0.1  \n [5] stringr_1.6.0   dplyr_1.2.0     purrr_1.2.2     readr_2.2.0    \n [9] tidyr_1.3.2     tibble_3.3.1    ggplot2_4.0.3   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2     Rcpp_1.1.1-1.1    \n [5] tidyselect_1.2.1   scales_1.4.0       yaml_2.3.12        fastmap_1.2.0     \n [9] R6_2.6.1           labeling_0.4.3     generics_0.1.4     knitr_1.51        \n[13] backports_1.5.1    htmlwidgets_1.6.4  chk_0.10.0         pillar_1.11.1     \n[17] RColorBrewer_1.1-3 tzdb_0.5.0         rlang_1.2.0        stringi_1.8.7     \n[21] xfun_0.57          S7_0.2.2           otel_0.2.0         timechange_0.4.0  \n[25] cli_3.6.5          withr_3.0.2        magrittr_2.0.4     digest_0.6.39     \n[29] grid_4.5.2         hms_1.1.4          lifecycle_1.0.5    vctrs_0.7.3       \n[33] evaluate_1.0.5     glue_1.8.0         farver_2.1.2       rmarkdown_2.31    \n[37] tools_4.5.2        pkgconfig_2.0.3    htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week3_session4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}