{
  "hash": "add9be859197e074e53a761b565e91c5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 2, Session 1 — Trees, random forests, gradient boosting\"\nsubtitle: \"Course 4 — Biostatistics Courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week2_session1_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Workflow labs** use the variant template:\nGoal → Approach → Execution → Check → Report.\n:::\n\n## Learning objectives\n\n- Fit a single decision tree, a random forest, and a gradient-boosted\n  model on the same data, and compare their error.\n- Read variable-importance output critically and know its biases.\n- Explain when a tree ensemble is preferable to a linear model and when\n  it is not.\n\n## Prerequisites\n\nCV from Session 1; regularisation from Session 2.\n\n## Background\n\nTree-based models divide feature space by axis-aligned splits and fit a\nconstant within each region. A single tree is interpretable but high\nvariance; averaging many trees with resampling and random feature\nsubsets gives random forests, which are among the strongest off-the-shelf\nmethods on tabular data. Gradient boosting takes a different route: it\nfits trees sequentially, each correcting the residuals of the last, and\nusually wins on tabular benchmarks when carefully tuned.\n\nTree methods make few assumptions about the functional form of the\nresponse and handle interactions automatically. Their limitations are\nextrapolation (flat beyond the training range), variable-importance\nmeasures that can be misleading when features are correlated, and a\ngeneral tendency to look better than they generalise unless honest\nresampling is used.\n\n::: {.content-visible when-format=\"html\"}\nWhen reporting a random forest or gradient-boosted model, report the\ntuning procedure, the out-of-bag or CV error, the variable-importance\nmethod, and — if the goal is scientific — a permutation-based importance\nto cross-check the default Gini/gain importance.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(rpart)\nlibrary(ranger)\nlibrary(xgboost)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Goal\n\nPredict `mpg` from `mtcars` with a single tree, a random forest, and\ngradient boosting; compare errors and importances.\n\n## 2. Approach\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- mtcars\nggplot(d, aes(wt, mpg, colour = factor(cyl))) +\n  geom_point() + labs(colour = \"cyl\")\n```\n\n::: {.cell-output-display}\n![](lab_week2_session1_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## 3. Execution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntree_fit <- rpart(mpg ~ ., data = d, cp = 0.01)\nrf_fit   <- ranger(mpg ~ ., data = d, importance = \"permutation\",\n                   num.trees = 500)\nxg_fit   <- xgboost(\n  data = as.matrix(d[, -1]), label = d$mpg,\n  nrounds = 100, eta = 0.05, max_depth = 3,\n  objective = \"reg:squarederror\", verbose = 0\n)\n```\n:::\n\n\n## 4. Check\n\nHonest error: CV for the tree and xgboost, OOB for ranger.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nK <- 5\nfolds <- sample(rep(1:K, length.out = nrow(d)))\nmse <- function(y, yhat) mean((y - yhat)^2)\n\nget_err <- function() {\n  err_tree <- err_rf <- err_xg <- numeric(K)\n  for (k in 1:K) {\n    tr <- folds != k; te <- folds == k\n    f_tr <- d[tr, ]; f_te <- d[te, ]\n    t1 <- rpart(mpg ~ ., data = f_tr, cp = 0.01)\n    r1 <- ranger(mpg ~ ., data = f_tr, num.trees = 500)\n    x1 <- xgboost(\n      data = as.matrix(f_tr[, -1]), label = f_tr$mpg,\n      nrounds = 100, eta = 0.05, max_depth = 3,\n      objective = \"reg:squarederror\", verbose = 0\n    )\n    err_tree[k] <- mse(f_te$mpg, predict(t1, f_te))\n    err_rf[k]   <- mse(f_te$mpg, predict(r1, f_te)$predictions)\n    err_xg[k]   <- mse(f_te$mpg, predict(x1, as.matrix(f_te[, -1])))\n  }\n  c(tree = mean(err_tree), rf = mean(err_rf), xgb = mean(err_xg))\n}\nerrs <- get_err()\nerrs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     tree        rf       xgb \n13.900260  4.814310  7.995655 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(var = names(rf_fit$variable.importance),\n       imp = as.numeric(rf_fit$variable.importance)) |>\n  arrange(desc(imp)) |>\n  ggplot(aes(reorder(var, imp), imp)) + geom_col() +\n  coord_flip() + labs(x = NULL, y = \"permutation importance\")\n```\n\n::: {.cell-output-display}\n![](lab_week2_session1_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## 5. Report\n\n> On `mtcars` (*n* = 32), 5-fold CV MSEs were\n> 13.9 (single tree),\n> 4.81 (random forest), and\n> 8 (gradient boosting). Permutation\n> importance from the random forest identified weight and displacement\n> as the dominant predictors.\n\nThe CV errors are close because the sample is tiny and the problem is\nclose to linear. On larger tabular problems the gap opens and\ngradient boosting typically wins after tuning; but the tiny-sample\nregime is where trees and boosting most often look like magic and\nalmost always lie.\n\n::: {.notes}\nPoint out that with n = 32, any CV estimate has very wide\nvariability. The example is pedagogical, not a benchmark.\n:::\n\n## Common pitfalls\n\n- Reporting the training error of a forest; always use OOB or CV.\n- Trusting Gini/gain importance for correlated predictors.\n- Letting xgboost overfit with low `eta` and high `nrounds` without\n  early stopping.\n\n## Further reading\n\n- Breiman L (2001), *Random forests*.\n- Chen T, Guestrin C (2016), *XGBoost: A scalable tree boosting\n  system*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] xgboost_3.2.1.1 ranger_0.18.0   rpart_4.1.27    lubridate_1.9.5\n [5] forcats_1.0.1   stringr_1.6.0   dplyr_1.2.0     purrr_1.2.2    \n [9] readr_2.2.0     tidyr_1.3.2     tibble_3.3.1    ggplot2_4.0.3  \n[13] tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] Matrix_1.7-5        gtable_0.3.6        jsonlite_2.0.0     \n [4] compiler_4.5.2      Rcpp_1.1.1-1.1      tidyselect_1.2.1   \n [7] parallel_4.5.2      scales_1.4.0        yaml_2.3.12        \n[10] fastmap_1.2.0       lattice_0.22-9      R6_2.6.1           \n[13] labeling_0.4.3      generics_0.1.4      knitr_1.51         \n[16] htmlwidgets_1.6.4   pillar_1.11.1       RColorBrewer_1.1-3 \n[19] tzdb_0.5.0          rlang_1.2.0         stringi_1.8.7      \n[22] xfun_0.57           S7_0.2.2            otel_0.2.0         \n[25] timechange_0.4.0    cli_3.6.5           withr_3.0.2        \n[28] magrittr_2.0.4      digest_0.6.39       grid_4.5.2         \n[31] hms_1.1.4           lifecycle_1.0.5     vctrs_0.7.3        \n[34] data.table_1.18.2.1 evaluate_1.0.5      glue_1.8.0         \n[37] farver_2.1.2        rmarkdown_2.31      tools_4.5.2        \n[40] pkgconfig_2.0.3     htmltools_0.5.9    \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week2_session1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}