{
  "hash": "41cc779d8f67375d6a412d97b724db0c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 2, Session 1 — Descriptive statistics and Table 1\"\nsubtitle: \"Course 1 — Biostatistics Courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week2_session1_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Workflow labs** use the variant template:\nGoal → Approach → Execution → Check → Report.\n:::\n\n## Learning objectives\n\n- Match the right summary statistic to the right variable type —\n  means for symmetric continuous, medians for skewed, counts and\n  percentages for categorical.\n- Build a publication-ready Table 1 with `gtsummary::tbl_summary()`.\n- Defend the choice of summary with a quick visual check.\n\n## Prerequisites\n\nLabs 1.3 through 1.5.\n\n## Background\n\nTable 1 is the first real table of almost every clinical paper. It\ndescribes the sample: who was in the study, in how many groups, with\nwhat characteristics, and — if the study has arms — how balanced those\narms are at baseline. A Table 1 that is built thoughtlessly hides an\nunbalanced comparison; a Table 1 that is built well anchors the rest\nof the paper.\n\nThe right summary depends on the variable. A continuous variable that\nis roughly symmetric is summarised by its mean and standard deviation;\none that is skewed or has heavy tails is summarised by its median and\ninterquartile range. A categorical variable is summarised by counts\nand percentages. Reporting the median of a balanced continuous variable\nis not wrong, but it is unusual; reporting the mean of a skewed\nvariable is often misleading.\n\ngtsummary packages these choices into a declarative API. You say\nwhich variables to include and which grouping variable to stratify by,\nand the table is built with sensible defaults. When you need\nnon-standard behaviour, you override per-variable.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(palmerpenguins)\nlibrary(gtsummary)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Goal\n\nProduce a Table 1 for the `penguins` dataset stratified by species,\nand back the choice of summary with a diagnostic plot.\n\n## 2. Approach\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- penguins |>\n  drop_na(species, sex, bill_length_mm, bill_depth_mm,\n          flipper_length_mm, body_mass_g)\n```\n:::\n\n\n## 3. Execution\n\nPick the right summary per variable. First, eyeball the shapes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat |>\n  pivot_longer(c(bill_length_mm, bill_depth_mm,\n                 flipper_length_mm, body_mass_g),\n               names_to = \"variable\", values_to = \"value\") |>\n  ggplot(aes(value, fill = species)) +\n  geom_histogram(bins = 20, alpha = 0.6, colour = \"grey30\",\n                 position = \"identity\") +\n  facet_wrap(~ variable, scales = \"free\") +\n  labs(x = NULL, y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](lab_week2_session1_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nAll four continuous variables are approximately symmetric within\nspecies, so mean (SD) is defensible. If a variable were skewed, we\nwould switch to median (IQR).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt1 <- dat |>\n  select(species, sex, bill_length_mm, bill_depth_mm,\n         flipper_length_mm, body_mass_g) |>\n  tbl_summary(\n    by = species,\n    statistic = list(\n      all_continuous() ~ \"{mean} ({sd})\",\n      all_categorical() ~ \"{n} ({p}%)\"\n    ),\n    digits = all_continuous() ~ 1,\n    label = list(\n      bill_length_mm    ~ \"Bill length (mm)\",\n      bill_depth_mm     ~ \"Bill depth (mm)\",\n      flipper_length_mm ~ \"Flipper length (mm)\",\n      body_mass_g       ~ \"Body mass (g)\",\n      sex               ~ \"Sex\"\n    )\n  ) |>\n  add_overall() |>\n  add_p()\nt1\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qeayjdrzqo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qeayjdrzqo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qeayjdrzqo thead, #qeayjdrzqo tbody, #qeayjdrzqo tfoot, #qeayjdrzqo tr, #qeayjdrzqo td, #qeayjdrzqo th {\n  border-style: none;\n}\n\n#qeayjdrzqo p {\n  margin: 0;\n  padding: 0;\n}\n\n#qeayjdrzqo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qeayjdrzqo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qeayjdrzqo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qeayjdrzqo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qeayjdrzqo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qeayjdrzqo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qeayjdrzqo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qeayjdrzqo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qeayjdrzqo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qeayjdrzqo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qeayjdrzqo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qeayjdrzqo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qeayjdrzqo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qeayjdrzqo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_left {\n  text-align: left;\n}\n\n#qeayjdrzqo .gt_center {\n  text-align: center;\n}\n\n#qeayjdrzqo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qeayjdrzqo .gt_font_normal {\n  font-weight: normal;\n}\n\n#qeayjdrzqo .gt_font_bold {\n  font-weight: bold;\n}\n\n#qeayjdrzqo .gt_font_italic {\n  font-style: italic;\n}\n\n#qeayjdrzqo .gt_super {\n  font-size: 65%;\n}\n\n#qeayjdrzqo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qeayjdrzqo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qeayjdrzqo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qeayjdrzqo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qeayjdrzqo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qeayjdrzqo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qeayjdrzqo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qeayjdrzqo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qeayjdrzqo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipPdmVyYWxsKiogIApOID0gMzMz\"><span class='gt_from_md'><strong>Overall</strong><br />\nN = 333</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipBZGVsaWUqKiAgCk4gPSAxNDY=\"><span class='gt_from_md'><strong>Adelie</strong><br />\nN = 146</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipDaGluc3RyYXAqKiAgCk4gPSA2OA==\"><span class='gt_from_md'><strong>Chinstrap</strong><br />\nN = 68</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_3\"><span data-qmd-base64=\"KipHZW50b28qKiAgCk4gPSAxMTk=\"><span class='gt_from_md'><strong>Gentoo</strong><br />\nN = 119</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sex</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">>0.9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    female</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">165 (50%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">73 (50%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">34 (50%)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">58 (49%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    male</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">168 (50%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">73 (50%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">34 (50%)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">61 (51%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Bill length (mm)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">44.0 (5.5)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">38.8 (2.7)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">48.8 (3.3)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">47.6 (3.1)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Bill depth (mm)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">17.2 (2.0)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">18.3 (1.2)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">18.4 (1.1)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">15.0 (1.0)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Flipper length (mm)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">201.0 (14.0)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">190.1 (6.5)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">195.8 (7.1)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">217.2 (6.6)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Body mass (g)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4,207.1 (805.2)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3,706.2 (458.6)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">3,733.1 (384.3)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">5,092.4 (501.5)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"6\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"biAoJSk7IE1lYW4gKFNEKQ==\"><span class='gt_from_md'>n (%); Mean (SD)</span></span></td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"6\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"UGVhcnNvbidzIENoaS1zcXVhcmVkIHRlc3Q7IEtydXNrYWwtV2FsbGlzIHJhbmsgc3VtIHRlc3Q=\"><span class='gt_from_md'>Pearson’s Chi-squared test; Kruskal-Wallis rank sum test</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n`add_p()` will run a t-test or ANOVA on continuous variables and a\nchi-square or Fisher's exact test on categorical, with sensible\ndefaults for sample size.\n\n## 4. Check\n\nValidate the gtsummary output against a hand computation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat |>\n  group_by(species) |>\n  summarise(\n    n = n(),\n    mean_mass = mean(body_mass_g),\n    sd_mass   = sd(body_mass_g),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  species       n mean_mass sd_mass\n  <fct>     <int>     <dbl>   <dbl>\n1 Adelie      146     3706.    459.\n2 Chinstrap    68     3733.    384.\n3 Gentoo      119     5092.    501.\n```\n\n\n:::\n:::\n\n\nThe group means and standard deviations must match the numbers in the\nbody-mass row of the Table 1.\n\n## 5. Report\n\n> Table 1 describes 333 penguins from three species in the\n> Palmer Archipelago. Body mass was highest in Gentoo\n> (5092\n> ± 501 g) and\n> lower in Adelie and Chinstrap. All four continuous variables were\n> approximately symmetric within species and are summarised as mean\n> (SD); sex was approximately balanced within each species.\n\nTable 1 is not a tool for hypothesis testing. The *p*-values in the\nrightmost column describe the data, not the biology. A\nstatistically-significant difference between arms at baseline in a\nrandomised trial is, by construction, a chance finding.\n\n::: {.notes}\nStress the distinction between Table 1 as description and Table 2 as\ninference. The audience will carry the habit into their own writing.\n:::\n\n## Common pitfalls\n\n- Reporting a mean for a skewed variable.\n- Using Table 1 as a place to \"prove balance\" with *p*-values in a\n  randomised trial.\n- Suppressing the missing-data row. Always report it.\n- Forgetting that `tbl_summary` drops NAs by default; check the count\n  at the bottom of each column.\n\n## Further reading\n\n- Sjoberg DD et al. *Reproducible summary tables with the gtsummary\n  package*. R Journal.\n- Altman DG. *Practical Statistics for Medical Research*, chapter on\n  describing data.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] gtsummary_2.5.0      palmerpenguins_0.1.1 lubridate_1.9.5     \n [4] forcats_1.0.1        stringr_1.6.0        dplyr_1.2.0         \n [7] purrr_1.2.2          readr_2.2.0          tidyr_1.3.2         \n[10] tibble_3.3.1         ggplot2_4.0.3        tidyverse_2.0.0     \n\nloaded via a namespace (and not attached):\n [1] gt_1.3.0           utf8_1.2.6         sass_0.4.10        generics_0.1.4    \n [5] xml2_1.5.2         stringi_1.8.7      hms_1.1.4          digest_0.6.39     \n [9] magrittr_2.0.4     evaluate_1.0.5     grid_4.5.2         timechange_0.4.0  \n[13] RColorBrewer_1.1-3 cards_0.7.1        fastmap_1.2.0      jsonlite_2.0.0    \n[17] cardx_0.3.2        backports_1.5.1    scales_1.4.0       cli_3.6.6         \n[21] rlang_1.2.0        litedown_0.9       commonmark_2.0.0   base64enc_0.1-6   \n[25] withr_3.0.2        yaml_2.3.12        otel_0.2.0         tools_4.5.2       \n[29] tzdb_0.5.0         broom_1.0.12       vctrs_0.7.3        R6_2.6.1          \n[33] lifecycle_1.0.5    fs_2.1.0           htmlwidgets_1.6.4  pkgconfig_2.0.3   \n[37] pillar_1.11.1      gtable_0.3.6       glue_1.8.0         xfun_0.57         \n[41] tidyselect_1.2.1   knitr_1.51         farver_2.1.2       htmltools_0.5.9   \n[45] rmarkdown_2.31     labeling_0.4.3     compiler_4.5.2     S7_0.2.2          \n[49] markdown_2.0      \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week2_session1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}