{
  "hash": "e8939891068969bb1257b1e1db64acdd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 4, Session 4 — Non-parametric tests\"\nsubtitle: \"Course 1 — #courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week4_session4_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Inference labs** use the five-step template:\nHypothesis → Visualise → Assumptions → Conduct → Conclude.\n:::\n\n## Learning objectives\n\n- Choose the right rank-based test for a given design — Wilcoxon\n  signed-rank, Mann-Whitney *U*, Kruskal-Wallis, sign test.\n- Run each in base R and interpret the output.\n- State what null hypothesis each test is really addressing (not\n  always \"medians are equal\").\n\n## Prerequisites\n\nLabs 3.4, 4.1.\n\n## Background\n\nNon-parametric tests make weaker distributional assumptions than the\nparametric tests that dominate the preceding labs. They tend to test\n*exchangeability* of distributions rather than equality of means, and\nthey operate on ranks of the data rather than on the raw values. When\nthe data are heavily skewed, ordinal, or small-sample, the\nnon-parametric alternatives are often the defensible default.\n\nThe workhorse set: Wilcoxon signed-rank for paired continuous data;\nMann-Whitney *U* (the `wilcox.test` with `paired = FALSE`) for two\nindependent groups; Kruskal-Wallis for three or more groups; sign\ntest as a cruder paired-data option based on the signs of\ndifferences alone.\n\nA common mistake is to read these tests as \"comparing medians\". They\ncompare *distributions*. Under additional assumptions — notably that\nthe two groups' distributions differ only by a location shift — the\nMann-Whitney *U* test does estimate a location shift, but that is a\nstronger assumption than the test itself requires.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Hypothesis\n\nThree scenarios:\n\nA. Paired: pre/post in 25 patients, skewed outcome. H0: no shift.\nB. Independent two-sample: outcome in two arms, skewed. H0: same\n   distribution.\nC. Three-group comparison: outcome across three centres. H0: same\n   distribution across all three.\n\n## 2. Visualise\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scenario A: paired, lognormal-ish\nn_a <- 25\npre <- exp(rnorm(n_a, 3, 0.3))\npost <- pre * exp(rnorm(n_a, -0.2, 0.3))\ndf_a <- tibble(id = seq_len(n_a), pre, post,\n               delta = post - pre)\n\n# Scenario B: independent two groups, lognormal\nn_b <- 30\ngrp <- rep(c(\"A\", \"B\"), each = n_b)\ny_b <- c(exp(rnorm(n_b, 3, 0.5)),\n         exp(rnorm(n_b, 3.4, 0.5)))\ndf_b <- tibble(grp, y = y_b)\n\n# Scenario C: three groups\nn_c <- 25\ncentre <- rep(c(\"X\", \"Y\", \"Z\"), each = n_c)\ny_c <- c(exp(rnorm(n_c, 3.0, 0.4)),\n         exp(rnorm(n_c, 3.2, 0.4)),\n         exp(rnorm(n_c, 3.5, 0.4)))\ndf_c <- tibble(centre, y = y_c)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_b |>\n  ggplot(aes(grp, y, fill = grp)) +\n  geom_boxplot(alpha = 0.6, colour = \"grey30\") +\n  labs(x = NULL, y = \"Outcome\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](lab_week4_session4_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n## 3. Assumptions\n\nWilcoxon signed-rank: paired observations; differences symmetric\naround the null. Mann-Whitney *U*: independent observations within and\nbetween groups; if you want a location-shift interpretation, the two\ndistributions should have the same shape. Kruskal-Wallis: independent\nobservations; same-shape assumption extends to all *k* groups.\n\n## 4. Conduct\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A: Wilcoxon signed-rank\nwt_a <- wilcox.test(df_a$post, df_a$pre, paired = TRUE,\n                    conf.int = TRUE)\n# Sign test: a simple binomial test on positive differences\nsigns <- sum(df_a$delta > 0)\nsign_test <- binom.test(signs, n_a, p = 0.5)\n\n# B: Mann-Whitney U\nwt_b <- wilcox.test(y ~ grp, data = df_b, conf.int = TRUE)\n\n# C: Kruskal-Wallis\nkw_c <- kruskal.test(y ~ centre, data = df_c)\n\nlist(wilcox_paired = wt_a,\n     sign_test = sign_test,\n     mann_whitney = wt_b,\n     kruskal_wallis = kw_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$wilcox_paired\n\n\tWilcoxon signed rank exact test\n\ndata:  df_a$post and df_a$pre\nV = 29, p-value = 0.000103\nalternative hypothesis: true location shift is not equal to 0\n95 percent confidence interval:\n -7.462659 -2.298395\nsample estimates:\n(pseudo)median \n     -4.709926 \n\n\n$sign_test\n\n\tExact binomial test\n\ndata:  signs and n_a\nnumber of successes = 4, number of trials = 25, p-value = 0.0009105\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.04537945 0.36082845\nsample estimates:\nprobability of success \n                  0.16 \n\n\n$mann_whitney\n\n\tWilcoxon rank sum exact test\n\ndata:  y by grp\nW = 239, p-value = 0.001525\nalternative hypothesis: true location shift is not equal to 0\n95 percent confidence interval:\n -17.224482  -3.592832\nsample estimates:\ndifference in location \n              -9.54957 \n\n\n$kruskal_wallis\n\n\tKruskal-Wallis rank sum test\n\ndata:  y by centre\nKruskal-Wallis chi-squared = 27.751, df = 2, p-value = 9.417e-07\n```\n\n\n:::\n:::\n\n\nFollow-up pairwise comparisons with Holm correction for C:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairwise.wilcox.test(df_c$y, df_c$centre, p.adjust.method = \"holm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using Wilcoxon rank sum exact test \n\ndata:  df_c$y and df_c$centre \n\n  X       Y      \nY 0.01436 -      \nZ 1.4e-06 0.00018\n\nP value adjustment method: holm \n```\n\n\n:::\n:::\n\n\n## 5. Concluding statement\n\n> **Paired comparison (A).** 25 patients, median change =\n> -4.1; Wilcoxon signed-rank *p* =\n> 10^{-4}, 95% CI on the Hodges-Lehmann estimate\n> -7.46 to\n> -2.3. Sign test *p* =\n> 9.1\\times 10^{-4}.\n>\n> **Two-group (B).** Mann-Whitney *p* =\n> 0.0015, 95% CI\n> -17.22 to\n> -3.59.\n>\n> **Three-group (C).** Kruskal-Wallis χ² =\n> 27.75, df = 2,\n> *p* = 9.4\\times 10^{-7}. Pairwise Wilcoxon tests with\n> Holm correction indicated the signal lay in the X vs Z contrast.\n\nNon-parametric tests are not free lunches. They trade a modest amount\nof power (about 5% vs a *t*-test when the *t*-test's assumptions\nhold) for robustness to distributional misspecification.\n\n::: {.notes}\nRemind the audience that a *t*-test with log-transformed data is\noften a cleaner answer than a Wilcoxon on the raw data.\n:::\n\n## Common pitfalls\n\n- Reading a Wilcoxon as a test of medians. It is a test of\n  distributional shift.\n- Using a rank test when the data are fine on the raw scale, and\n  sacrificing power unnecessarily.\n- Forgetting to adjust for multiplicity after a Kruskal-Wallis.\n\n## Further reading\n\n- Hollander M, Wolfe DA. *Nonparametric Statistical Methods*.\n- Conover WJ. *Practical Nonparametric Statistics*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.5 forcats_1.0.1   stringr_1.6.0   dplyr_1.2.1    \n [5] purrr_1.2.2     readr_2.2.0     tidyr_1.3.2     tibble_3.3.1   \n [9] ggplot2_4.0.3   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2     tidyselect_1.2.1  \n [5] scales_1.4.0       yaml_2.3.12        fastmap_1.2.0      R6_2.6.1          \n [9] labeling_0.4.3     generics_0.1.4     knitr_1.51         htmlwidgets_1.6.4 \n[13] pillar_1.11.1      RColorBrewer_1.1-3 tzdb_0.5.0         rlang_1.2.0       \n[17] stringi_1.8.7      xfun_0.57          S7_0.2.2           otel_0.2.0        \n[21] timechange_0.4.0   cli_3.6.6          withr_3.0.2        magrittr_2.0.4    \n[25] digest_0.6.39      grid_4.5.2         hms_1.1.4          lifecycle_1.0.5   \n[29] vctrs_0.7.3        evaluate_1.0.5     glue_1.8.1         farver_2.1.2      \n[33] rmarkdown_2.31     tools_4.5.2        pkgconfig_2.0.3    htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week4_session4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}