{
  "hash": "3d028902247b029fcfb2cec358439099",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 3, Session 4 — Poisson and negative-binomial regression\"\nsubtitle: \"Course 2 — Biostatistics Courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week3_session4_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Inference labs** use the five-step template:\nHypothesis → Visualise → Assumptions → Conduct → Conclude.\n:::\n\n## Learning objectives\n\n- Fit a Poisson GLM for counts with `glm(family = poisson)` and use an\n  offset for exposure.\n- Diagnose overdispersion and switch to negative-binomial regression\n  with `MASS::glm.nb` when needed.\n- Report incidence rate ratios with intervals.\n\n## Prerequisites\n\nWeek 3 Session 1 on logistic regression.\n\n## Background\n\nCounts with a known exposure are the natural habitat of the Poisson\nGLM: number of events per person-year, per square metre, per trap\nnight. The canonical link is the log, so the exponentiated coefficient\nis an incidence rate ratio. Exposure enters the model as an offset —\na term with a fixed coefficient of 1 on the log scale.\n\nThe Poisson model assumes variance equals the mean. Most real count\ndata violate this, with variance growing faster than the mean.\nOverdispersion inflates Type-I error when ignored. Checking the ratio\nof residual deviance to its degrees of freedom gives a quick read;\nwhen it is substantially above 1, the negative-binomial GLM (or a\nquasi-Poisson variance) is a better fit.\n\n::: {.content-visible when-format=\"html\"}\nPoisson regression without an offset is a common trap. If the\ndenominators vary, a coefficient on an exposure variable is\nconfounded with exposure; the offset separates the two and restores\nthe interpretation of the log-rate ratio.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(MASS)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Hypothesis\n\nSimulate counts of events with a dispersion parameter larger than 1\n(so negative-binomial is the correct model), plus a known exposure.\n\n## 2. Visualise\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 300\nx <- rnorm(n)\nexposure <- runif(n, 0.5, 2)\nmu <- exposure * exp(0.5 + 0.4 * x)\n# negative-binomial counts with theta = 2 (overdispersion)\ny <- rnegbin(n, mu = mu, theta = 2)\ndat <- tibble(x, exposure, y)\n\nggplot(dat, aes(x, y)) +\n  geom_point(alpha = 0.6) +\n  labs(x = \"x\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](lab_week3_session4_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## 3. Assumptions\n\nIndependent counts; correct mean structure; for Poisson, variance = mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_p <- glm(y ~ x + offset(log(exposure)), data = dat, family = poisson)\n# dispersion\ndev_over_df <- deviance(fit_p) / df.residual(fit_p)\ndev_over_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.918715\n```\n\n\n:::\n:::\n\n\nDispersion >> 1 signals negative-binomial.\n\n## 4. Conduct\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_nb <- glm.nb(y ~ x + offset(log(exposure)), data = dat)\n\nbind_rows(\n  tidy(fit_p, conf.int = TRUE, exponentiate = TRUE) |> mutate(model = \"Poisson\"),\n  tidy(fit_nb, conf.int = TRUE, exponentiate = TRUE) |> mutate(model = \"NB\")\n) |>\n  filter(term == \"x\") |>\n  dplyr::select(model, estimate, conf.low, conf.high, std.error)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  model   estimate conf.low conf.high std.error\n  <chr>      <dbl>    <dbl>     <dbl>     <dbl>\n1 Poisson     1.35     1.25      1.47    0.0416\n2 NB          1.35     1.21      1.52    0.0579\n```\n\n\n:::\n:::\n\n\nThe estimates are similar but the NB standard error is larger and\nhonest.\n\n## 5. Concluding statement\n\n> Event counts increased with x (NB IRR per unit x =\n> 1.35; 95% CI\n> 1.21 to\n> 1.52). Poisson residual\n> deviance indicated overdispersion; we therefore report the\n> negative-binomial fit as primary.\n\n::: {.notes}\nEncourage students to always fit both and report the NB when\ndispersion is above 1.2 or so; it will very rarely hurt.\n:::\n\n## Common pitfalls\n\n- Forgetting the offset when denominators vary.\n- Using Poisson when overdispersion is present.\n- Reporting the rate ratio without an interval.\n\n## Further reading\n\n- McCullagh P, Nelder JA. *Generalized Linear Models*, ch. 6.\n- Hilbe JM. *Negative Binomial Regression*.\n- Zeileis A, Kleiber C, Jackman S (2008), *Regression models for count data*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] MASS_7.3-65     broom_1.0.12    lubridate_1.9.5 forcats_1.0.1  \n [5] stringr_1.6.0   dplyr_1.2.0     purrr_1.2.2     readr_2.2.0    \n [9] tidyr_1.3.2     tibble_3.3.1    ggplot2_4.0.3   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2     tidyselect_1.2.1  \n [5] scales_1.4.0       yaml_2.3.12        fastmap_1.2.0      R6_2.6.1          \n [9] labeling_0.4.3     generics_0.1.4     knitr_1.51         backports_1.5.1   \n[13] htmlwidgets_1.6.4  pillar_1.11.1      RColorBrewer_1.1-3 tzdb_0.5.0        \n[17] rlang_1.2.0        utf8_1.2.6         stringi_1.8.7      xfun_0.57         \n[21] S7_0.2.2           otel_0.2.0         timechange_0.4.0   cli_3.6.6         \n[25] withr_3.0.2        magrittr_2.0.4     digest_0.6.39      grid_4.5.2        \n[29] hms_1.1.4          lifecycle_1.0.5    vctrs_0.7.3        evaluate_1.0.5    \n[33] glue_1.8.0         farver_2.1.2       rmarkdown_2.31     tools_4.5.2       \n[37] pkgconfig_2.0.3    htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week3_session4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}