{
  "hash": "2b8e0904266be6e205d3b219762be62b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 4, Session 1 — Two-sample and paired t-tests\"\nsubtitle: \"Course 1 — Biostatistics Courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week4_session1_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Inference labs** use the five-step template:\nHypothesis → Visualise → Assumptions → Conduct → Conclude.\n:::\n\n## Learning objectives\n\n- Choose between Student's and Welch's *t*-test, and between paired\n  and independent-samples tests.\n- Compute Cohen's *d* and Hedges' *g* as effect sizes.\n- Report a two-sample comparison with point estimate, CI, and effect\n  size.\n\n## Prerequisites\n\nLab 3.4.\n\n## Background\n\nThe two-sample *t*-test compares the means of two independent groups.\nStudent's version assumes equal variances across the groups; Welch's\ndoes not. In most applied settings Welch's is the safer default — it\nbehaves nearly as well as Student's when variances are actually equal\nand much better when they are not. The `t.test()` default in R is\nWelch.\n\nWhen the same subjects are measured twice, the samples are paired and\nthe two measurements are correlated. Ignoring the pairing inflates the\nstandard error and lowers power. Pairing is handled by computing the\nwithin-subject difference and running a one-sample *t*-test on it.\n\nEffect sizes remove units from the comparison. Cohen's *d* is the\nstandardised mean difference: the mean difference divided by the\npooled standard deviation. Hedges' *g* applies a small-sample\ncorrection. Both are essential alongside a *p*-value — a large *d* at\na small *n* will often produce a non-significant *p*, but the *d* is\nstill a warning that a larger study might find a real effect.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(effectsize)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Hypothesis\n\nScenario A (independent): mean systolic blood pressure in treatment\nvs placebo.\n\n- H0: μ_trt = μ_pla, H1: μ_trt ≠ μ_pla, α = 0.05.\n\nScenario B (paired): SBP before and after a four-week intervention in\nthe same 30 patients.\n\n- H0: mean within-subject change = 0, H1: ≠ 0.\n\n## 2. Visualise\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 40\ntrt <- rnorm(n, mean = 135, sd = 12)\npla <- rnorm(n, mean = 142, sd = 12)\ndf_ind <- tibble(\n  arm = rep(c(\"placebo\", \"treatment\"), each = n),\n  sbp = c(pla, trt)\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_ind |>\n  ggplot(aes(arm, sbp, fill = arm)) +\n  geom_boxplot(alpha = 0.6, colour = \"grey30\") +\n  labs(x = NULL, y = \"SBP (mmHg)\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](lab_week4_session1_files/figure-html/unnamed-chunk-2-1.png){width=576}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn2 <- 30\npre  <- rnorm(n2, 148, 10)\npost <- pre - rnorm(n2, 5, 7)  # true mean drop of 5\ndf_pair <- tibble(id = seq_len(n2), pre = pre, post = post) |>\n  mutate(delta = post - pre)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_pair |>\n  pivot_longer(c(pre, post), names_to = \"time\", values_to = \"sbp\") |>\n  mutate(time = factor(time, levels = c(\"pre\", \"post\"))) |>\n  ggplot(aes(time, sbp, group = id)) +\n  geom_line(alpha = 0.4) +\n  geom_point(alpha = 0.6) +\n  labs(x = NULL, y = \"SBP (mmHg)\")\n```\n\n::: {.cell-output-display}\n![](lab_week4_session1_files/figure-html/unnamed-chunk-4-1.png){width=576}\n:::\n:::\n\n\n## 3. Assumptions\n\nIndependent *t*: approximate normality of the sample means; Welch's\ndoes not require equal variances. Paired *t*: approximate normality\nof the within-subject differences.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_pair |>\n  ggplot(aes(sample = delta)) +\n  stat_qq() + stat_qq_line(colour = \"firebrick\") +\n  labs(x = \"Theoretical\", y = \"Sample (pair differences)\")\n```\n\n::: {.cell-output-display}\n![](lab_week4_session1_files/figure-html/unnamed-chunk-5-1.png){width=480}\n:::\n:::\n\n\n## 4. Conduct\n\n### Two-sample (Welch)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntt_welch <- t.test(sbp ~ arm, data = df_ind, var.equal = FALSE)\ntt_welch\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  sbp by arm\nt = 2.9095, df = 72.3, p-value = 0.004807\nalternative hypothesis: true difference in means between group placebo and group treatment is not equal to 0\n95 percent confidence interval:\n  2.655371 14.209770\nsample estimates:\n  mean in group placebo mean in group treatment \n               142.9581                134.5256 \n```\n\n\n:::\n:::\n\n\n### Two-sample Student (for comparison)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntt_student <- t.test(sbp ~ arm, data = df_ind, var.equal = TRUE)\ntt_student\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  sbp by arm\nt = 2.9095, df = 78, p-value = 0.004715\nalternative hypothesis: true difference in means between group placebo and group treatment is not equal to 0\n95 percent confidence interval:\n  2.662545 14.202597\nsample estimates:\n  mean in group placebo mean in group treatment \n               142.9581                134.5256 \n```\n\n\n:::\n:::\n\n\n### Paired\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntt_paired <- t.test(df_pair$post, df_pair$pre, paired = TRUE)\ntt_paired\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  df_pair$post and df_pair$pre\nt = -2.4747, df = 29, p-value = 0.01943\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -5.7941048 -0.5505107\nsample estimates:\nmean difference \n      -3.172308 \n```\n\n\n:::\n:::\n\n\n### Effect size\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_ind    <- cohens_d(sbp ~ arm, data = df_ind)\ng_ind    <- hedges_g(sbp ~ arm, data = df_ind)\nd_paired <- cohens_d(df_pair$post, df_pair$pre, paired = TRUE)\nlist(d_ind = d_ind, g_ind = g_ind, d_paired = d_paired)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$d_ind\nCohen's d |       95% CI\n------------------------\n0.65      | [0.20, 1.10]\n\n- Estimated using pooled SD.\n$g_ind\nHedges' g |       95% CI\n------------------------\n0.64      | [0.20, 1.09]\n\n- Estimated using pooled SD.\n$d_paired\nCohen's d |         95% CI\n--------------------------\n-0.45     | [-0.82, -0.07]\n```\n\n\n:::\n:::\n\n\n## 5. Concluding statement\n\n> **Independent comparison.** Mean SBP was\n> 134.5 mmHg (SD 14.7) in the\n> treatment arm and 143 (SD\n> 11) in placebo. A Welch's *t*-test gave\n> *t*(72.3) =\n> 2.91, *p* =\n> 0.0048, mean difference\n> 8.4 mmHg (95% CI\n> -14.2 to\n> -2.7). Cohen's *d* =\n> 0.65 (Hedges' *g* =\n> 0.64), a small-to-medium effect.\n\n> **Paired comparison.** The within-subject change\n> (post − pre) had mean -3.2 mmHg (SD\n> 7); paired *t*-test *t*(29)\n> = -2.47, *p* =\n> 0.019, 95% CI\n> -5.8 to\n> -0.6.\n\nThe effect size is the number that generalises. A *p*-value tells\nyou whether to reject; *d* and its CI tell you how much.\n\n::: {.notes}\nInsist that students always look at the paired-difference Q-Q plot.\nThe before/after line plot is pretty; the Q-Q plot is diagnostic.\n:::\n\n## Common pitfalls\n\n- Running an independent-samples *t* on paired data and losing power.\n- Reporting Student's *t* in the era of Welch; there is rarely a good\n  reason.\n- Reporting *p* without *d* (or an equivalent effect size).\n- Confusing effect size with statistical significance.\n\n## Further reading\n\n- Delacre M et al. (2017). *Why psychologists should by default use\n  Welch's t-test*.\n- Cohen J. *Statistical Power Analysis for the Behavioral Sciences*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] effectsize_1.0.2 lubridate_1.9.5  forcats_1.0.1    stringr_1.6.0   \n [5] dplyr_1.2.0      purrr_1.2.2      readr_2.2.0      tidyr_1.3.2     \n [9] tibble_3.3.1     ggplot2_4.0.3    tidyverse_2.0.0 \n\nloaded via a namespace (and not attached):\n [1] sandwich_3.1-1     generics_0.1.4     stringi_1.8.7      lattice_0.22-9    \n [5] hms_1.1.4          digest_0.6.39      magrittr_2.0.4     evaluate_1.0.5    \n [9] grid_4.5.2         timechange_0.4.0   estimability_1.5.1 RColorBrewer_1.1-3\n[13] mvtnorm_1.3-7      fastmap_1.2.0      Matrix_1.7-5       jsonlite_2.0.0    \n[17] survival_3.8-6     multcomp_1.4-30    scales_1.4.0       TH.data_1.1-5     \n[21] codetools_0.2-20   cli_3.6.6          rlang_1.2.0        splines_4.5.2     \n[25] withr_3.0.2        yaml_2.3.12        otel_0.2.0         tools_4.5.2       \n[29] datawizard_1.3.1   tzdb_0.5.0         coda_0.19-4.1      bayestestR_0.17.0 \n[33] vctrs_0.7.3        R6_2.6.1           zoo_1.8-15         lifecycle_1.0.5   \n[37] emmeans_2.0.3      htmlwidgets_1.6.4  MASS_7.3-65        insight_1.5.0     \n[41] pkgconfig_2.0.3    pillar_1.11.1      gtable_0.3.6       glue_1.8.0        \n[45] xfun_0.57          tidyselect_1.2.1   parameters_0.28.3  knitr_1.51        \n[49] xtable_1.8-8       farver_2.1.2       htmltools_0.5.9    labeling_0.4.3    \n[53] rmarkdown_2.31     compiler_4.5.2     S7_0.2.2          \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week4_session1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}