{
  "hash": "d912b49a2c6144d578331a91cba6d5c3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 1, Session 3 — Data types, tidy data, accuracy and precision\"\nsubtitle: \"Course 1 — #courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week1_session3_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Workflow labs** use the variant template:\nGoal → Approach → Execution → Check → Report.\n:::\n\n## Learning objectives\n\n- Classify a variable as nominal, ordinal, interval, or ratio and\n  explain why the distinction dictates what summaries are legal.\n- Reshape a rectangular dataset between wide and long form with\n  `pivot_longer()` and `pivot_wider()`.\n- Separate accuracy, precision, and bias by simulation, and say why a\n  precise instrument can still be wrong.\n\n## Prerequisites\n\nLab 1.2 (toolchain).\n\n## Background\n\nStatistics is largely the study of variation, and variation must be\nmeasured. Before we calculate anything we need to say what kind of\nvariable we are looking at. A *nominal* variable labels groups\nwithout order. An *ordinal* variable orders them but does not quantify\nthe distance between them. *Interval* and *ratio* variables do quantify\ndistances, and ratio variables have a true zero. Tools that average an\nordinal variable or compute a standard deviation on a category code\nproduce numbers, but not answers.\n\nTidy data is a convention, not a requirement, but adopting it pays\nimmediate dividends: every variable gets a column, every observation a\nrow, and every value a cell. Real datasets arrive in other shapes, so a\nlarge part of the job is reshaping them until they conform. The tools\nare `pivot_longer()` and `pivot_wider()`, and they are the two\nfunctions you will use most often in a working week.\n\n::: {.content-visible when-format=\"html\"}\nThe accuracy/precision/bias triangle is borrowed from measurement\ntheory. Accuracy is how close a measurement is to truth on average.\nPrecision is how tightly repeated measurements cluster. Bias is a\nsystematic offset from truth. An instrument can be precise but biased\n(tight cluster off-target), accurate but imprecise (wide cluster\ncentred on truth), or — the goal — both.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Goal\n\nMove a small simulated clinical dataset between wide and long forms\nand quantify accuracy, precision, and bias in a simulated measurement\nprocess.\n\n## 2. Approach\n\nWe simulate three repeat measurements of blood pressure on twelve\npatients at two visits. This is a realistic wide-format dataset with\na within-patient structure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclinic <- tibble(\n  id = sprintf(\"P%02d\", 1:12),\n  sex = sample(c(\"F\", \"M\"), 12, replace = TRUE),\n  visit1_sbp1 = rnorm(12, 140, 10),\n  visit1_sbp2 = rnorm(12, 140, 10),\n  visit1_sbp3 = rnorm(12, 140, 10),\n  visit2_sbp1 = rnorm(12, 135, 10),\n  visit2_sbp2 = rnorm(12, 135, 10),\n  visit2_sbp3 = rnorm(12, 135, 10)\n)\nclinic |> select(id, starts_with(\"visit1\")) |> head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  id    visit1_sbp1 visit1_sbp2 visit1_sbp3\n  <chr>       <dbl>       <dbl>       <dbl>\n1 P01          155.        116.        145.\n2 P02          139.        153.        147.\n3 P03          160.        137.        150.\n```\n\n\n:::\n:::\n\n\n## 3. Execution\n\nReshape to a long form where each row is one reading.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong <- clinic |>\n  pivot_longer(\n    cols = starts_with(\"visit\"),\n    names_to = c(\"visit\", \"reading\"),\n    names_pattern = \"visit(\\\\d)_sbp(\\\\d)\",\n    values_to = \"sbp\"\n  ) |>\n  mutate(visit = factor(paste0(\"V\", visit)),\n         reading = as.integer(reading))\nhead(long)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  id    sex   visit reading   sbp\n  <chr> <chr> <fct>   <int> <dbl>\n1 P01   F     V1          1  155.\n2 P01   F     V1          2  116.\n3 P01   F     V1          3  145.\n4 P01   F     V2          1  143.\n5 P01   F     V2          2  136.\n6 P01   F     V2          3  138.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong |>\n  ggplot(aes(visit, sbp, colour = sex)) +\n  geom_jitter(width = 0.1, alpha = 0.6) +\n  labs(x = NULL, y = \"SBP (mmHg)\")\n```\n\n::: {.cell-output-display}\n![](lab_week1_session3_files/figure-html/unnamed-chunk-3-1.png){width=576}\n:::\n:::\n\n\nThe long format makes it trivial to summarise by visit, by patient, or\nby visit-and-patient. The same plot in wide format would require\ncustom code for each visit column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Collapse three readings per visit to a mean.\nby_visit <- long |>\n  group_by(id, visit, sex) |>\n  summarise(sbp_mean = mean(sbp), .groups = \"drop\")\n\n# Pivot back to wide if the downstream analysis needs it.\nwide <- by_visit |> pivot_wider(names_from = visit, values_from = sbp_mean)\nhead(wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  id    sex      V1    V2\n  <chr> <chr> <dbl> <dbl>\n1 P01   F      138.  139.\n2 P02   F      146.  137.\n3 P03   F      149.  136.\n4 P04   F      132.  139.\n5 P05   M      145.  119.\n6 P06   M      146.  140.\n```\n\n\n:::\n:::\n\n\n## 4. Check\n\nSimulate an instrument with a known truth (say, a calibrated reference\nof 120) and compare three candidate devices with different\naccuracy/precision profiles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntruth <- 120\nn <- 500\ndevices <- tibble(\n  device_A = rnorm(n, mean = 120, sd = 1),   # accurate & precise\n  device_B = rnorm(n, mean = 125, sd = 1),   # precise, biased\n  device_C = rnorm(n, mean = 120, sd = 5)    # accurate on average, imprecise\n) |>\n  pivot_longer(everything(), names_to = \"device\", values_to = \"reading\")\n\nsummary_table <- devices |>\n  group_by(device) |>\n  summarise(mean = mean(reading),\n            sd = sd(reading),\n            bias = mean(reading) - truth,\n            rmse = sqrt(mean((reading - truth)^2)))\nsummary_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  device    mean    sd    bias  rmse\n  <chr>    <dbl> <dbl>   <dbl> <dbl>\n1 device_A  120. 0.974 -0.0280 0.974\n2 device_B  125. 1.02   4.95   5.06 \n3 device_C  120. 4.83  -0.0819 4.83 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndevices |>\n  ggplot(aes(reading, fill = device)) +\n  geom_density(alpha = 0.5, colour = NA) +\n  geom_vline(xintercept = truth, linetype = 2) +\n  labs(x = \"Reading\", y = \"Density\")\n```\n\n::: {.cell-output-display}\n![](lab_week1_session3_files/figure-html/unnamed-chunk-6-1.png){width=576}\n:::\n:::\n\n\n## 5. Report\n\n> In a simulated calibration experiment (*n* = 500 draws per device),\n> the unbiased precise device had bias = -0.03\n> mmHg and SD = 0.97; the biased precise\n> device had bias = 4.95 and the same SD;\n> the imprecise unbiased device had bias = -0.08\n> but SD = 4.83.\n> Root mean squared error captures accuracy overall and is the quantity\n> to minimise.\n\nThe lesson is that *bias* and *variance* are separately identifiable.\nA device that is consistent is not necessarily correct, and a device\nthat is correct on average may still be unusable on a single reading.\n\n::: {.notes}\nUse the density plot to anchor the intuition — three distributions,\none dashed line at the truth. Ask the audience which device they would\nuse for a single reading, and which for a large calibration study.\n:::\n\n## Common pitfalls\n\n- Treating ordinal codes (1 = mild, 2 = moderate, 3 = severe) as if\n  the steps were equal.\n- Forcing data to stay wide because that is how the spreadsheet\n  happened to arrive.\n- Judging a measurement by precision alone. A small SD with a big bias\n  is still the wrong number.\n- Using the mean to summarise a nominal variable.\n\n## Further reading\n\n- Wickham H (2014), *Tidy Data*. Journal of Statistical Software.\n- Altman DG, Bland JM (1983), *Measurement in medicine*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.5 forcats_1.0.1   stringr_1.6.0   dplyr_1.2.1    \n [5] purrr_1.2.2     readr_2.2.0     tidyr_1.3.2     tibble_3.3.1   \n [9] ggplot2_4.0.3   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2     tidyselect_1.2.1  \n [5] scales_1.4.0       yaml_2.3.12        fastmap_1.2.0      R6_2.6.1          \n [9] labeling_0.4.3     generics_0.1.4     knitr_1.51         htmlwidgets_1.6.4 \n[13] pillar_1.11.1      RColorBrewer_1.1-3 tzdb_0.5.0         rlang_1.2.0       \n[17] utf8_1.2.6         stringi_1.8.7      xfun_0.57          S7_0.2.2          \n[21] otel_0.2.0         timechange_0.4.0   cli_3.6.6          withr_3.0.2       \n[25] magrittr_2.0.4     digest_0.6.39      grid_4.5.2         hms_1.1.4         \n[29] lifecycle_1.0.5    vctrs_0.7.3        evaluate_1.0.5     glue_1.8.1        \n[33] farver_2.1.2       rmarkdown_2.31     tools_4.5.2        pkgconfig_2.0.3   \n[37] htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week1_session3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}