{
  "hash": "b9e0dbf47cee8c5ff470801918f47743",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 3, Session 4 — One-sample t-test and one-proportion test\"\nsubtitle: \"Course 1 — #courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week3_session4_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Inference labs** use the five-step template:\nHypothesis → Visualise → Assumptions → Conduct → Conclude.\n:::\n\n## Learning objectives\n\n- State a one-sample null and alternative hypothesis for a continuous\n  outcome and for a proportion.\n- Run `t.test(mu = )` and `prop.test()` / `binom.test()` and\n  interpret the output.\n- Apply the full five-step inference template in one working pass.\n\n## Prerequisites\n\nLabs 2.5, 3.3.\n\n## Background\n\nThe one-sample *t*-test asks whether the mean of a continuous outcome\ndiffers from a pre-specified value μ₀. It is the inference analogue of\nTable 1: a single-column calculation asking whether the sample is\nconsistent with a named population mean. The test statistic is\n(x̄ − μ₀) / (s/√*n*), compared to a *t* distribution on *n* − 1\ndegrees of freedom.\n\nThe one-proportion test does the same for a binary outcome. When the\nsample is large we use `prop.test()`, which is a Wald-type test based\non the normal approximation to the binomial; when the sample is small,\n`binom.test()` gives an exact test based on the binomial PMF. Both\nreturn a *p*-value, a point estimate, and a CI.\n\nThese are the simplest tests in the course, but the five-step template\n— hypothesis, visualise, assumptions, conduct, conclude — is the same\ntemplate used in every later inference lab. Getting the template into\nmuscle memory here pays dividends throughout the rest of the course.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Hypothesis\n\nScenario A (continuous): fasting blood glucose in a random sample of\n`n = 40` patients from a clinic. Reference mean μ₀ = 95 mg/dL in a\nhealthy population. Two-sided test.\n\n- H0: μ = 95\n- H1: μ ≠ 95\n- α = 0.05\n\nScenario B (proportion): of 120 patients offered a new screening\nprogramme, *k* = 78 accepted. Reference acceptance rate π₀ = 0.60.\n\n- H0: π = 0.60\n- H1: π ≠ 0.60\n- α = 0.05\n\n## 2. Visualise\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 40\nglucose <- rnorm(n, mean = 100, sd = 12)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(glucose) |>\n  ggplot(aes(glucose)) +\n  geom_histogram(bins = 15, fill = \"grey60\", colour = \"white\") +\n  geom_vline(xintercept = 95, linetype = 2) +\n  geom_vline(xintercept = mean(glucose), colour = \"firebrick\") +\n  labs(x = \"Fasting glucose (mg/dL)\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](lab_week3_session4_files/figure-html/unnamed-chunk-2-1.png){width=576}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccept <- 78\ntotal  <- 120\ntibble(state = c(\"accepted\", \"declined\"),\n       count = c(accept, total - accept))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  state    count\n  <chr>    <dbl>\n1 accepted    78\n2 declined    42\n```\n\n\n:::\n:::\n\n\n## 3. Assumptions\n\n*t*-test: approximate normality of the sample mean, which — by the\ncentral limit theorem — holds for *n* = 40 unless the underlying\ndistribution is strongly skewed. Check with a Q-Q plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(glucose) |>\n  ggplot(aes(sample = glucose)) +\n  stat_qq() + stat_qq_line(colour = \"firebrick\") +\n  labs(x = \"Theoretical\", y = \"Sample\")\n```\n\n::: {.cell-output-display}\n![](lab_week3_session4_files/figure-html/unnamed-chunk-4-1.png){width=480}\n:::\n:::\n\n\nProportion test: independent binary trials, same success probability.\nFor `prop.test` the large-sample normal approximation needs\n*np*₀ ≥ 5 and *n*(1 − *p*₀) ≥ 5; both are satisfied.\n\n## 4. Conduct\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntt <- t.test(glucose, mu = 95)\ntt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  glucose\nt = 1.9513, df = 39, p-value = 0.05824\nalternative hypothesis: true mean is not equal to 95\n95 percent confidence interval:\n  94.83431 104.21683\nsample estimates:\nmean of x \n 99.52557 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt_large <- prop.test(x = accept, n = total, p = 0.60)\npt_exact <- binom.test(x = accept, n = total, p = 0.60)\nlist(prop_test = pt_large, binom_test = pt_exact)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$prop_test\n\n\t1-sample proportions test with continuity correction\n\ndata:  accept out of total, null probability 0.6\nX-squared = 1.0503, df = 1, p-value = 0.3054\nalternative hypothesis: true p is not equal to 0.6\n95 percent confidence interval:\n 0.5569559 0.7332917\nsample estimates:\n   p \n0.65 \n\n\n$binom_test\n\n\tExact binomial test\n\ndata:  accept and total\nnumber of successes = 78, number of trials = 120, p-value = 0.3054\nalternative hypothesis: true probability of success is not equal to 0.6\n95 percent confidence interval:\n 0.5576053 0.7347977\nsample estimates:\nprobability of success \n                  0.65 \n```\n\n\n:::\n:::\n\n\n## 5. Concluding statement\n\n> **Scenario A.** In a sample of 40 patients, mean fasting glucose\n> was 99.5 mg/dL (SD\n> 14.7). The one-sample *t*-test against μ₀ = 95\n> gave *t*(39) = 1.95,\n> *p* = 0.058, mean difference\n> 4.5 (95% CI\n> -0.2 to\n> 9.2).\n\n> **Scenario B.** Acceptance was 78 of 120\n> (65%); the exact one-proportion\n> test against π₀ = 0.60 gave *p* =\n> 0.31, 95% CI\n> 0.56 to\n> 0.73.\n\nThe two scenarios share a template. The glossary changes — mean and\nSD for continuous, count and proportion for binary — but the five\nsteps are the same.\n\n::: {.notes}\nMake the template rigid here. In subsequent labs the students will\nriff on it; the rigidity at this stage is the anchor.\n:::\n\n## Common pitfalls\n\n- Running a one-sided test to \"rescue\" a borderline two-sided\n  *p*-value.\n- Reporting the *p*-value without the mean difference and its CI.\n- Using `prop.test` when the expected count of either outcome is very\n  small; use `binom.test` there.\n\n## Further reading\n\n- Rosner B. *Fundamentals of Biostatistics*, chapter on one-sample\n  inference.\n- Altman DG, *Confidence intervals rather than p values*, BMJ 1986.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.5 forcats_1.0.1   stringr_1.6.0   dplyr_1.2.1    \n [5] purrr_1.2.2     readr_2.2.0     tidyr_1.3.2     tibble_3.3.1   \n [9] ggplot2_4.0.3   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2     tidyselect_1.2.1  \n [5] scales_1.4.0       yaml_2.3.12        fastmap_1.2.0      R6_2.6.1          \n [9] labeling_0.4.3     generics_0.1.4     knitr_1.51         htmlwidgets_1.6.4 \n[13] pillar_1.11.1      RColorBrewer_1.1-3 tzdb_0.5.0         rlang_1.2.0       \n[17] utf8_1.2.6         stringi_1.8.7      xfun_0.57          S7_0.2.2          \n[21] otel_0.2.0         timechange_0.4.0   cli_3.6.6          withr_3.0.2       \n[25] magrittr_2.0.4     digest_0.6.39      grid_4.5.2         hms_1.1.4         \n[29] lifecycle_1.0.5    vctrs_0.7.3        evaluate_1.0.5     glue_1.8.1        \n[33] farver_2.1.2       rmarkdown_2.31     tools_4.5.2        pkgconfig_2.0.3   \n[37] htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week3_session4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}