{
  "hash": "d451736e51666f7cb2124ce55d004759",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 3, Session 3 — Maximum likelihood estimation\"\nsubtitle: \"Course 1 — Biostatistics Courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week3_session3_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Inference labs** use the five-step template:\nHypothesis → Visualise → Assumptions → Conduct → Conclude.\n:::\n\n## Learning objectives\n\n- Write a log-likelihood for a simple model and find its maximum.\n- Use Fisher information to obtain an asymptotic standard error and\n  confidence interval.\n- Relate the MLE to intuitive estimators (sample mean, sample rate).\n\n## Prerequisites\n\nLab 3.1.\n\n## Background\n\nMaximum likelihood is the workhorse of parametric inference. Given a\nparametric family for the data — normal, Poisson, binomial — the MLE\nis the parameter value that makes the observed data most probable.\nUnder mild regularity conditions the MLE is consistent (it converges\nto the truth), asymptotically unbiased, and asymptotically\nnormal with variance given by the inverse of Fisher information.\n\nFisher information quantifies how sharply the log-likelihood peaks at\nits maximum. A sharply peaked likelihood gives a precise estimate\n(small variance); a flat one gives a vague estimate. The standard\nerror of an MLE is the square root of 1/*n* times the inverse of the\nFisher information per observation.\n\nIn the simple cases we treat here the MLE coincides with the\nintuitive estimator — the mean for a normal, the sample rate for a\nPoisson — but the machinery generalises to any likelihood.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Hypothesis\n\nEstimate (i) the mean of a normal and (ii) the rate of a Poisson by\nmaximum likelihood, recover standard errors from Fisher information,\nand build Wald confidence intervals.\n\n## 2. Visualise\n\nNormal data with known σ = 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 50\nmu_true <- 5\nsigma <- 2\nx <- rnorm(n, mean = mu_true, sd = sigma)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- tibble(mu = seq(3.5, 6.5, length.out = 300)) |>\n  mutate(loglik = sapply(mu, function(m) sum(dnorm(x, m, sigma, log = TRUE))))\nggplot(grid, aes(mu, loglik)) +\n  geom_line() +\n  geom_vline(xintercept = mean(x), linetype = 2, colour = \"firebrick\") +\n  labs(x = expression(mu), y = \"log-likelihood\")\n```\n\n::: {.cell-output-display}\n![](lab_week3_session3_files/figure-html/unnamed-chunk-2-1.png){width=576}\n:::\n:::\n\n\nThe likelihood is peaked at the sample mean — that is the MLE.\n\n## 3. Assumptions\n\nNormal model: iid, constant σ. Poisson model: iid counts, constant\nrate over a fixed exposure. Fisher information is evaluated *at the\nMLE* for the Wald standard error.\n\n## 4. Conduct\n\n### Normal mean by MLE\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmle_mu <- mean(x)\n# Fisher information for mu in normal with known sigma is n / sigma^2.\nI_mu <- n / sigma^2\nse_mu <- 1 / sqrt(I_mu)\nci_mu <- mle_mu + c(-1, 1) * qnorm(0.975) * se_mu\ntibble(mle = mle_mu, se = se_mu,\n       ci_low = ci_mu[1], ci_high = ci_mu[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n    mle    se ci_low ci_high\n  <dbl> <dbl>  <dbl>   <dbl>\n1  4.93 0.283   4.37    5.48\n```\n\n\n:::\n:::\n\n\n### Normal mean by numeric optimisation (sanity check)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnll <- function(mu) -sum(dnorm(x, mu, sigma, log = TRUE))\nopt <- optim(0, nll, method = \"Brent\", lower = 0, upper = 10, hessian = TRUE)\nopt$par        # MLE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.928656\n```\n\n\n:::\n\n```{.r .cell-code}\nsqrt(1 / opt$hessian[1, 1])  # SE from observed information\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2828427\n```\n\n\n:::\n:::\n\n\n### Poisson rate by MLE\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- rpois(100, lambda = 3.2)\nmle_lambda <- mean(y)\n# Fisher information for lambda: n / lambda. At MLE use 1/mle_lambda per obs.\nI_lambda <- length(y) / mle_lambda\nse_lambda <- 1 / sqrt(I_lambda)\nci_lambda <- mle_lambda + c(-1, 1) * qnorm(0.975) * se_lambda\ntibble(mle = mle_lambda, se = se_lambda,\n       ci_low = ci_lambda[1], ci_high = ci_lambda[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n    mle    se ci_low ci_high\n  <dbl> <dbl>  <dbl>   <dbl>\n1  3.24  0.18   2.89    3.59\n```\n\n\n:::\n:::\n\n\n### Likelihood surface for a two-parameter model (μ, σ)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurf <- expand_grid(\n  mu = seq(3.5, 6.5, length.out = 80),\n  s  = seq(1, 3.5, length.out = 80)\n) |>\n  rowwise() |>\n  mutate(ll = sum(dnorm(x, mu, s, log = TRUE))) |>\n  ungroup()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(surf, aes(mu, s, fill = ll)) +\n  geom_tile() +\n  geom_contour(aes(z = ll), colour = \"white\") +\n  scale_fill_viridis_c() +\n  labs(x = expression(mu), y = expression(sigma), fill = \"log-L\")\n```\n\n::: {.cell-output-display}\n![](lab_week3_session3_files/figure-html/unnamed-chunk-7-1.png){width=480}\n:::\n:::\n\n\n## 5. Concluding statement\n\n> The MLE of the normal mean from *n* = 50 observations at σ = 2\n> was 4.929 (Fisher-information SE = 0.283;\n> 95% Wald CI 4.37 to 5.48),\n> recovering the true μ = 5. The MLE of the Poisson rate from *n* =\n> 100 observations was 3.24 (SE\n> 0.18; CI 2.89 to\n> 3.59). Observed-information SEs from `optim`\n> agreed with the expected-information calculation.\n\nThe MLE is the general-purpose engine behind linear regression,\nlogistic regression, Cox models, and the bulk of parametric inference\nin this course. The machinery — likelihood, information, SE — is the\nsame in each case.\n\n::: {.notes}\nDraw the likelihood surface by hand first. The contour plot is the\nintuition the students should take away.\n:::\n\n## Common pitfalls\n\n- Reporting a Wald CI when the sample is small. Profile CIs are more\n  accurate in that regime.\n- Evaluating Fisher information at a wrong value of the parameter.\n  Use the MLE.\n- Forgetting that the MLE is not always unbiased for finite *n* —\n  only asymptotically.\n\n## Further reading\n\n- Casella G, Berger RL. *Statistical Inference*, chapter on point\n  estimation.\n- Cox DR. *Principles of Statistical Inference*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.5 forcats_1.0.1   stringr_1.6.0   dplyr_1.2.0    \n [5] purrr_1.2.2     readr_2.2.0     tidyr_1.3.2     tibble_3.3.1   \n [9] ggplot2_4.0.3   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2     tidyselect_1.2.1  \n [5] scales_1.4.0       yaml_2.3.12        fastmap_1.2.0      R6_2.6.1          \n [9] labeling_0.4.3     generics_0.1.4     isoband_0.3.0      knitr_1.51        \n[13] htmlwidgets_1.6.4  pillar_1.11.1      RColorBrewer_1.1-3 tzdb_0.5.0        \n[17] rlang_1.2.0        stringi_1.8.7      xfun_0.57          S7_0.2.2          \n[21] otel_0.2.0         viridisLite_0.4.3  timechange_0.4.0   cli_3.6.6         \n[25] withr_3.0.2        magrittr_2.0.4     digest_0.6.39      grid_4.5.2        \n[29] hms_1.1.4          lifecycle_1.0.5    vctrs_0.7.3        evaluate_1.0.5    \n[33] glue_1.8.0         farver_2.1.2       rmarkdown_2.31     tools_4.5.2       \n[37] pkgconfig_2.0.3    htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week3_session3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}