{
  "hash": "af3b2018ebd5b6c564197cac6e9689c9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 3, Session 2 — ANCOVA in RCTs (baseline adjustment)\"\nsubtitle: \"Course 2 — Biostatistics Courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week3_session2_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Inference labs** use the five-step template:\nHypothesis → Visualise → Assumptions → Conduct → Conclude.\n:::\n\n## Learning objectives\n\n- Choose between change scores, post-only, and ANCOVA in an RCT\n  analysis plan.\n- Fit an ANCOVA model and read the treatment effect as an\n  adjusted-mean difference.\n- Show that ANCOVA is more efficient than the change-score approach\n  when baseline and follow-up are correlated.\n\n## Prerequisites\n\nWeek 1 regression; Week 2 one-way ANOVA.\n\n## Background\n\nIn a randomised trial with a continuous outcome measured at baseline\nand follow-up, three analyses are common: compare the post-intervention\nmeans, compare the change scores, or use analysis of covariance\n(ANCOVA) with baseline as a covariate. Randomisation ensures all three\nare unbiased in expectation, but they are not equally efficient.\n\nANCOVA weights the baseline by its observed correlation with the\nfollow-up and is therefore always at least as efficient as the\nchange-score approach, and much more efficient when that correlation is\nmoderate. Change scores are equivalent to ANCOVA with the baseline\nslope constrained to 1; post-only is ANCOVA with the slope constrained\nto 0. When neither constraint matches the data, efficiency is lost.\n\n::: {.content-visible when-format=\"html\"}\nRegression to the mean (Week 4 Session 1) is the mechanical reason\nANCOVA wins. Patients with unusually high baselines tend to have\nlower follow-ups whether they are treated or not; ANCOVA uses that\npattern, change-score analysis pretends it does not exist.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Hypothesis\n\nSimulate a trial with baseline and follow-up correlated at r = 0.6,\nthen compare the three analyses.\n\n## 2. Visualise\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 200\nbaseline <- rnorm(n, 140, 15)\narm <- rep(c(\"placebo\", \"active\"), each = n / 2)\n# true treatment effect on follow-up: -5\nfollowup <- 0.6 * (baseline - 140) + 140 +\n  ifelse(arm == \"active\", -5, 0) + rnorm(n, 0, 12)\ndat <- tibble(baseline, followup, arm,\n              change = followup - baseline) |>\n  mutate(arm = factor(arm, levels = c(\"placebo\", \"active\")))\n\nggplot(dat, aes(baseline, followup, colour = arm)) +\n  geom_point(alpha = 0.6) +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(x = \"Baseline\", y = \"Follow-up\")\n```\n\n::: {.cell-output-display}\n![](lab_week3_session2_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## 3. Assumptions\n\nRandomisation; linear relationship between baseline and follow-up;\nequal slopes across arms (tested with an interaction term).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_int <- lm(followup ~ arm * baseline, data = dat)\ntidy(fit_int) |> filter(term == \"armactive:baseline\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  term               estimate std.error statistic p.value\n  <chr>                 <dbl>     <dbl>     <dbl>   <dbl>\n1 armactive:baseline    0.120     0.112      1.07   0.285\n```\n\n\n:::\n:::\n\n\nIf the interaction is small, pool the slopes in the ANCOVA.\n\n## 4. Conduct\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_post   <- lm(followup ~ arm, data = dat)\nfit_change <- lm(change ~ arm, data = dat)\nfit_ancova <- lm(followup ~ arm + baseline, data = dat)\n\nbind_rows(\n  tidy(fit_post, conf.int = TRUE) |> mutate(model = \"post only\"),\n  tidy(fit_change, conf.int = TRUE) |> mutate(model = \"change\"),\n  tidy(fit_ancova, conf.int = TRUE) |> mutate(model = \"ANCOVA\")\n) |>\n  filter(term == \"armactive\") |>\n  dplyr::select(model, estimate, std.error, conf.low, conf.high)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  model     estimate std.error conf.low conf.high\n  <chr>        <dbl>     <dbl>    <dbl>     <dbl>\n1 post only    -5.56      1.95    -9.41   -1.71  \n2 change       -3.76      1.87    -7.44   -0.0760\n3 ANCOVA       -4.59      1.61    -7.77   -1.41  \n```\n\n\n:::\n:::\n\n\nThe three estimates should all be around −5; the ANCOVA standard error\nshould be the smallest.\n\n## 5. Concluding statement\n\n> In a simulated trial (*n* = 200), ANCOVA estimated the\n> treatment effect at\n> -4.59 units (95% CI\n> -7.77 to\n> -1.41) with a smaller\n> standard error than either the post-only or change-score analyses.\n> ANCOVA is the prespecified primary analysis in most continuous-outcome\n> RCTs.\n\n::: {.notes}\nSay out loud: *baseline is not a covariate you can be accused of\nchoosing to inflate the effect* — it is fixed before randomisation.\n:::\n\n## Common pitfalls\n\n- Adjusting for post-baseline covariates (not covered here, but a\n  classic trap).\n- Using a change score when baseline and follow-up are strongly\n  correlated.\n- Dropping observations with missing baselines instead of imputing or\n  prespecifying a policy.\n\n## Further reading\n\n- Senn S (2006), *Change from baseline and analysis of covariance...*\n- Vickers AJ, Altman DG (2001), *Analysing controlled trials with…*\n- ICH E9 (R1) Addendum on Estimands.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] broom_1.0.12    lubridate_1.9.5 forcats_1.0.1   stringr_1.6.0  \n [5] dplyr_1.2.0     purrr_1.2.2     readr_2.2.0     tidyr_1.3.2    \n [9] tibble_3.3.1    ggplot2_4.0.3   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] Matrix_1.7-5       gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2    \n [5] tidyselect_1.2.1   splines_4.5.2      scales_1.4.0       yaml_2.3.12       \n [9] fastmap_1.2.0      lattice_0.22-9     R6_2.6.1           labeling_0.4.3    \n[13] generics_0.1.4     knitr_1.51         backports_1.5.1    htmlwidgets_1.6.4 \n[17] pillar_1.11.1      RColorBrewer_1.1-3 tzdb_0.5.0         rlang_1.2.0       \n[21] utf8_1.2.6         stringi_1.8.7      xfun_0.57          S7_0.2.2          \n[25] otel_0.2.0         timechange_0.4.0   cli_3.6.5          mgcv_1.9-4        \n[29] withr_3.0.2        magrittr_2.0.4     digest_0.6.39      grid_4.5.2        \n[33] hms_1.1.4          nlme_3.1-169       lifecycle_1.0.5    vctrs_0.7.3       \n[37] evaluate_1.0.5     glue_1.8.0         farver_2.1.2       rmarkdown_2.31    \n[41] tools_4.5.2        pkgconfig_2.0.3    htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week3_session2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}