{
  "hash": "4179fb4a6c46b3d865e4664cc896f87d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 1, Session 3 — Adaptive, non-inferiority, equivalence trials\"\nsubtitle: \"Course 3 — #courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week1_session3_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Inference lab** using the five-step template:\nHypothesis → Visualise → Assumptions → Conduct → Conclude.\n:::\n\n## Learning objectives\n\n- Distinguish superiority, non-inferiority, and equivalence trials\n  by their null hypotheses.\n- Choose a non-inferiority margin and say what it means clinically.\n- Run and plot a non-inferiority test with a confidence interval\n  versus the margin.\n\n## Prerequisites\n\nCourse 1 inference and Course 2 confidence intervals.\n\n## Background\n\nA superiority trial asks whether a new treatment beats the\ncomparator. A non-inferiority (NI) trial asks whether the new\ntreatment is *not worse than* the comparator by more than a\npre-specified margin (often called Δ). An equivalence trial asks\nwhether the new treatment is neither better nor worse than the\ncomparator by more than Δ on either side. These are distinct\nstatistical questions and they require different designs,\nanalyses, and sample sizes.\n\nThe NI margin is the hardest thing about an NI trial. It has to be\nsmall enough that clinicians and patients would trade it for the\nbenefits of the new treatment (lower cost, fewer side effects,\neasier administration), but not so small that the trial is\ninfeasible. Regulators will often ask for a margin no larger than a\ndefined fraction of the historical treatment effect of the\ncomparator versus placebo.\n\nAdaptive trials modify some aspect of the design (sample size, arm\nallocation, the decision rule) during the trial based on interim\nresults, using pre-specified rules. Group sequential designs, for\nexample, stop early for overwhelming efficacy or for futility, while\nspending Type I error according to a chosen alpha-spending function.\n\n::: {.content-visible when-format=\"html\"}\nA one-sided 97.5% confidence interval that stays on the correct side\nof the margin is the operational test in most NI trials. Graphically,\nthis is a forest plot where you check that the interval does not\ncross the margin line.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Hypothesis\n\nH0: the new treatment is worse than the comparator by more than Δ\n= 3 units on a continuous outcome.\nH1: the new treatment is not worse by more than Δ.\n\n## 2. Visualise\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 150\ntrial <- tibble(\n  arm = rep(c(\"comparator\", \"new\"), each = n),\n  y   = c(rnorm(n, 70, 10), rnorm(n, 69, 10))\n)\n\ntrial |>\n  ggplot(aes(arm, y, fill = arm)) +\n  geom_boxplot(alpha = 0.6, colour = \"grey30\") +\n  labs(x = NULL, y = \"Outcome\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](lab_week1_session3_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## 3. Assumptions\n\nIndependent observations, roughly normal within-arm residuals, and a\npre-specified margin declared before looking at the data. The\n*direction* of the test matters: we test whether the lower bound of\nthe mean difference (new − comparator) is above −Δ.\n\n## 4. Conduct\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- t.test(y ~ arm, data = trial)\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  y by arm\nt = 0.75382, df = 297.66, p-value = 0.4516\nalternative hypothesis: true difference in means between group comparator and group new is not equal to 0\n95 percent confidence interval:\n -1.386395  3.107936\nsample estimates:\nmean in group comparator        mean in group new \n                69.71260                 68.85182 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndelta <- 3\nci <- fit$conf.int\nest <- diff(rev(fit$estimate))  # new - comparator\nni_pass <- ci[1] > -delta\ntibble(estimate = est, low = ci[1], high = ci[2], margin = -delta, ni_pass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  estimate   low  high margin ni_pass\n     <dbl> <dbl> <dbl>  <dbl> <lgl>  \n1    0.861 -1.39  3.11     -3 TRUE   \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(estimate = est, low = ci[1], high = ci[2]) |>\n  ggplot(aes(x = estimate, y = 1)) +\n  geom_point(size = 3) +\n  geom_errorbarh(aes(xmin = low, xmax = high), height = 0.1) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", colour = \"grey40\") +\n  geom_vline(xintercept = -delta, colour = \"firebrick\") +\n  labs(x = \"Mean difference (new - comparator)\", y = NULL) +\n  theme(axis.text.y = element_blank())\n```\n\n::: {.cell-output-display}\n![](lab_week1_session3_files/figure-html/unnamed-chunk-4-1.png){width=480}\n:::\n:::\n\n\n## 5. Concluding statement\n\n> The new treatment had a mean difference of 0.86 versus\n> comparator (95% CI: -1.39 to 3.11).\n> With a pre-specified non-inferiority margin of Δ = 3, the new\n> treatment met the\n> non-inferiority criterion because the lower bound\n> exceeded −Δ.\n\n### A word on adaptive designs\n\nAdaptive designs work when the adaptation rules and the alpha spent\nat each look are pre-specified. Running an interim analysis with the\nhope of extending the trial if it looks promising — without a pre-\nspecified rule — inflates Type I error and destroys the trial's\ninferential warranty.\n\n::: {.notes}\nA common exam trap is to confuse \"fails to reject superiority\" with\n\"establishes non-inferiority\". They are not the same thing.\n:::\n\n## Common pitfalls\n\n- Picking the NI margin after seeing the data.\n- Using a two-sided superiority test and claiming non-inferiority.\n- Running an \"interim look\" without a pre-specified spending rule.\n- Treating equivalence and non-inferiority as interchangeable.\n\n## Further reading\n\n- Piaggio G et al. (2012), *CONSORT extension for non-inferiority\n  and equivalence trials*.\n- Jennison C, Turnbull BW. *Group Sequential Methods with\n  Applications to Clinical Trials*.\n- FDA (2016), *Non-Inferiority Clinical Trials to Establish\n  Effectiveness*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.5 forcats_1.0.1   stringr_1.6.0   dplyr_1.2.1    \n [5] purrr_1.2.2     readr_2.2.0     tidyr_1.3.2     tibble_3.3.1   \n [9] ggplot2_4.0.3   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2     tidyselect_1.2.1  \n [5] scales_1.4.0       yaml_2.3.12        fastmap_1.2.0      R6_2.6.1          \n [9] labeling_0.4.3     generics_0.1.4     knitr_1.51         htmlwidgets_1.6.4 \n[13] pillar_1.11.1      RColorBrewer_1.1-3 tzdb_0.5.0         rlang_1.2.0       \n[17] stringi_1.8.7      xfun_0.57          S7_0.2.2           otel_0.2.0        \n[21] timechange_0.4.0   cli_3.6.6          withr_3.0.2        magrittr_2.0.4    \n[25] digest_0.6.39      grid_4.5.2         hms_1.1.4          lifecycle_1.0.5   \n[29] vctrs_0.7.3        evaluate_1.0.5     glue_1.8.1         farver_2.1.2      \n[33] rmarkdown_2.31     tools_4.5.2        pkgconfig_2.0.3    htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week1_session3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}