{
  "hash": "d978d388e35eb0a0bc43220191562a40",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 4, Session 2 — Two proportions, chi-square, risk and odds\"\nsubtitle: \"Course 1 — #courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week4_session2_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Inference labs** use the five-step template:\nHypothesis → Visualise → Assumptions → Conduct → Conclude.\n:::\n\n## Learning objectives\n\n- Compare two proportions with `prop.test()` and `fisher.test()` and\n  say when each is preferred.\n- Compute risk ratio, odds ratio, and risk difference with\n  confidence intervals.\n- Run a chi-square goodness-of-fit test against a named distribution.\n\n## Prerequisites\n\nLabs 2.4, 3.4.\n\n## Background\n\nTwo-proportion tests ask whether the rate of an event differs between\ntwo groups. In a 2x2 table, two exposure groups (say, treatment and\ncontrol) each produce a fraction of events. The chi-square test\ncompares the observed counts to those expected under independence;\nFisher's exact test computes the probability of a table as extreme\nor more extreme directly from the hypergeometric distribution and is\npreferred when expected cell counts are small.\n\nThe effect can be expressed in several ways. The risk difference is\nthe difference of the two proportions. The risk ratio is their ratio —\nthe event rate in the treated group, relative to control. The odds\nratio is the ratio of the odds. In a case-control study the risk\nratio is not directly estimable; the odds ratio is. In a cohort study\nboth are estimable and the risk ratio is usually more intuitive.\n\nGoodness-of-fit tests compare a vector of observed counts to a vector\nof expected proportions under a named distribution — whether a die is\nfair, whether a set of genotype frequencies matches Hardy-Weinberg,\nwhether arrivals over an hour are Poisson. The test statistic is the\nsame chi-square; the interpretation is \"is the distribution consistent\nwith a named model?\"\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Hypothesis\n\nTwo-by-two: `treatment` vs `control`, outcome `event` vs `none`.\n\n- H0: event rate is independent of treatment.\n- H1: rates differ.\n- α = 0.05.\n\n## 2. Visualise\n\nSimulate: 200 per arm, event rate 0.25 in control, 0.15 in treatment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_per <- 200\nsim <- tibble(\n  arm = rep(c(\"control\", \"treatment\"), each = n_per),\n  event = c(rbinom(n_per, 1, 0.25),\n            rbinom(n_per, 1, 0.15))\n)\ntab <- table(arm = sim$arm, event = sim$event)\ntab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           event\narm           0   1\n  control   148  52\n  treatment 167  33\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas_tibble(tab) |>\n  mutate(arm = factor(arm, levels = c(\"control\", \"treatment\")),\n         event = recode(event, `0` = \"no event\", `1` = \"event\")) |>\n  ggplot(aes(arm, n, fill = event)) +\n  geom_col(position = \"fill\", alpha = 0.7) +\n  labs(x = NULL, y = \"Proportion\", fill = NULL)\n```\n\n::: {.cell-output-display}\n![](lab_week4_session2_files/figure-html/unnamed-chunk-2-1.png){width=480}\n:::\n:::\n\n\n## 3. Assumptions\n\nChi-square requires expected cell counts ≥ 5. Fisher has no such\nconstraint and is exact at any size. Random assignment or\nrepresentative sampling is assumed. Independence of observations is\nessential.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(tab)$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           event\narm             0    1\n  control   157.5 42.5\n  treatment 157.5 42.5\n```\n\n\n:::\n:::\n\n\nAll expected counts large; chi-square is appropriate.\n\n## 4. Conduct\n\n\n::: {.cell}\n\n```{.r .cell-code}\nct <- chisq.test(tab, correct = FALSE)\nft <- fisher.test(tab)\npt <- prop.test(x = tab[, \"1\"], n = rowSums(tab), correct = FALSE)\nlist(chisq = ct, fisher = ft, prop = pt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$chisq\n\n\tPearson's Chi-squared test\n\ndata:  tab\nX-squared = 5.3931, df = 1, p-value = 0.02022\n\n\n$fisher\n\n\tFisher's Exact Test for Count Data\n\ndata:  tab\np-value = 0.02743\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 0.3331919 0.9418077\nsample estimates:\nodds ratio \n 0.5632336 \n\n\n$prop\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  tab[, \"1\"] out of rowSums(tab)\nX-squared = 5.3931, df = 1, p-value = 0.02022\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.01536478 0.17463522\nsample estimates:\nprop 1 prop 2 \n 0.260  0.165 \n```\n\n\n:::\n:::\n\n\n### Effect sizes: RD, RR, OR\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_ctrl <- tab[\"control\",   \"1\"] / sum(tab[\"control\", ])\np_trt  <- tab[\"treatment\", \"1\"] / sum(tab[\"treatment\", ])\n\nrd <- p_trt - p_ctrl\n\nrr <- p_trt / p_ctrl\n# Log-based Wald CI for RR\nse_log_rr <- sqrt(\n  (1 - p_trt)  / (p_trt  * sum(tab[\"treatment\", ])) +\n  (1 - p_ctrl) / (p_ctrl * sum(tab[\"control\",   ]))\n)\nci_rr <- exp(log(rr) + c(-1, 1) * qnorm(0.975) * se_log_rr)\n\nor <- (tab[\"treatment\", \"1\"] * tab[\"control\", \"0\"]) /\n      (tab[\"treatment\", \"0\"] * tab[\"control\", \"1\"])\nse_log_or <- sqrt(sum(1 / tab))\nci_or <- exp(log(or) + c(-1, 1) * qnorm(0.975) * se_log_or)\n\ntibble(effect = c(\"RD\", \"RR\", \"OR\"),\n       est = c(rd, rr, or),\n       ci_low = c(pt$conf.int[1], ci_rr[1], ci_or[1]),\n       ci_high = c(pt$conf.int[2], ci_rr[2], ci_or[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  effect    est ci_low ci_high\n  <chr>   <dbl>  <dbl>   <dbl>\n1 RD     -0.095 0.0154   0.175\n2 RR      0.635 0.430    0.937\n3 OR      0.562 0.345    0.917\n```\n\n\n:::\n:::\n\n\n### Goodness-of-fit example\n\nTest whether 600 simulated genotype counts match Hardy-Weinberg\nproportions at allele frequency 0.3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs <- c(AA = 260, Aa = 290, aa = 50)\npAA <- 0.7^2; paa <- 0.3^2; pAa <- 2 * 0.7 * 0.3\nexp_probs <- c(AA = pAA, Aa = pAa, aa = paa)\ngof <- chisq.test(obs, p = exp_probs)\ngof\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  obs\nX-squared = 9.9584, df = 2, p-value = 0.006879\n```\n\n\n:::\n:::\n\n\n## 5. Concluding statement\n\n> Event rates were 0.26 in control and\n> 0.165 in treatment (RD\n> -0.095; RR 0.63, 95% CI\n> 0.43 to 0.94; OR\n> 0.56, 95% CI 0.34 to\n> 0.92). Chi-square test χ² =\n> 5.39, df = 1,\n> *p* = 0.02. The Hardy-Weinberg\n> goodness-of-fit test on simulated genotypes gave χ² =\n> 9.96 (df = 2, *p* =\n> 0.0069).\n\nReport RR or OR alongside the *p*-value. In a cohort design prefer\nRR, which is the quantity clinicians translate directly to practice.\n\n::: {.notes}\nRemind students that OR and RR diverge when the outcome is common.\nThis is the single most-quoted basic epidemiology point in Course 2.\n:::\n\n## Common pitfalls\n\n- Reporting an OR when a RR is meaningful and more interpretable.\n- Using the continuity correction (the default in `prop.test` and\n  `chisq.test`) by habit; it is conservative.\n- Running a chi-square when expected counts are small; use Fisher.\n- Treating independent observations as if repeated measures weren't.\n\n## Further reading\n\n- Altman DG. *Practical Statistics for Medical Research*, chapter\n  10–11.\n- Agresti A. *Categorical Data Analysis*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.5 forcats_1.0.1   stringr_1.6.0   dplyr_1.2.1    \n [5] purrr_1.2.2     readr_2.2.0     tidyr_1.3.2     tibble_3.3.1   \n [9] ggplot2_4.0.3   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2     tidyselect_1.2.1  \n [5] scales_1.4.0       yaml_2.3.12        fastmap_1.2.0      R6_2.6.1          \n [9] labeling_0.4.3     generics_0.1.4     knitr_1.51         htmlwidgets_1.6.4 \n[13] pillar_1.11.1      RColorBrewer_1.1-3 tzdb_0.5.0         rlang_1.2.0       \n[17] utf8_1.2.6         stringi_1.8.7      xfun_0.57          S7_0.2.2          \n[21] otel_0.2.0         timechange_0.4.0   cli_3.6.6          withr_3.0.2       \n[25] magrittr_2.0.4     digest_0.6.39      grid_4.5.2         hms_1.1.4         \n[29] lifecycle_1.0.5    vctrs_0.7.3        evaluate_1.0.5     glue_1.8.1        \n[33] farver_2.1.2       rmarkdown_2.31     tools_4.5.2        pkgconfig_2.0.3   \n[37] htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week4_session2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}