{
  "hash": "3506755753103ea084b45c992c2ec077",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 1, Session 2 — Simple linear regression\"\nsubtitle: \"Course 2 — Biostatistics Courses\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n  revealjs:\n    output-file: \"lab_week1_session2_slides.html\"\n    theme: [default, ../../assets/slides.scss]\n    slide-number: c/t\n    progress: true\n    scrollable: true\n    transition: none\n    preview-links: auto\nexecute:\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\n**Inference labs** use the five-step template:\nHypothesis → Visualise → Assumptions → Conduct → Conclude.\n:::\n\n## Learning objectives\n\n- Fit a simple linear regression with `lm()` and read the output.\n- Produce a tidy coefficient table with intervals using `broom`.\n- Draw the fitted line on the scatterplot and express the slope in the\n  units of the variables.\n\n## Prerequisites\n\nSession 1 of this week; basic comfort with ggplot2.\n\n## Background\n\nSimple linear regression models the mean of a response Y as a linear\nfunction of a single predictor X. The model is Y = β₀ + β₁X + ε with\nthe error term ε assumed independent, zero-mean, and of constant\nvariance. The slope β₁ is the expected change in Y for a one-unit\nchange in X; the intercept β₀ is the expected Y at X = 0, which is\nsometimes meaningful and sometimes only a device for anchoring the\nline.\n\nAlthough the formulas are old, the habits they require are modern:\nalways plot first, always report an interval, and always read the slope\nback in the units of the variables. A regression coefficient is only\nuseful if the reader can imagine the units on the axis.\n\n::: {.content-visible when-format=\"html\"}\nThe default `summary()` printout from `lm()` is dense. A clean way to\nread a fit is to use `broom::tidy()` for coefficients and\n`broom::glance()` for global quantities such as R² and residual\nstandard error, and then plot the line on the data to sanity-check.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(palmerpenguins)\nset.seed(42)\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## 1. Hypothesis\n\nAmong Adelie penguins, does bill length predict body mass?\n\nNull: slope of body mass on bill length is zero.\nAlternative: slope is non-zero.\n\n## 2. Visualise\n\n\n::: {.cell}\n\n```{.r .cell-code}\nad <- penguins |>\n  filter(species == \"Adelie\") |>\n  drop_na(bill_length_mm, body_mass_g)\n\nggplot(ad, aes(bill_length_mm, body_mass_g)) +\n  geom_point(alpha = 0.6, colour = \"grey30\") +\n  geom_smooth(method = \"lm\", se = TRUE, colour = \"steelblue\") +\n  labs(x = \"Bill length (mm)\", y = \"Body mass (g)\")\n```\n\n::: {.cell-output-display}\n![](lab_week1_session2_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nThe cloud climbs gently from left to right. The smoothed line is an\nhonest guess at the conditional mean.\n\n## 3. Assumptions\n\nLinearity, independence, homoscedasticity, and approximate normality of\nresiduals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- lm(body_mass_g ~ bill_length_mm, data = ad)\npar(mfrow = c(2, 2))\nplot(fit)\n```\n\n::: {.cell-output-display}\n![](lab_week1_session2_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\nResiduals vs fitted is patternless; QQ is close to straight. No single\npoint dominates.\n\n## 4. Conduct\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(fit, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term           estimate std.error statistic  p.value conf.low conf.high\n  <chr>             <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)        34.9     458.     0.0761 9.39e- 1   -871.       941.\n2 bill_length_mm     94.5      11.8    8.01   2.95e-13     71.2      118.\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(fit) |> select(r.squared, adj.r.squared, sigma, p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  r.squared adj.r.squared sigma  p.value\n      <dbl>         <dbl> <dbl>    <dbl>\n1     0.301         0.297  385. 2.95e-13\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslope <- coef(fit)[2]\nci <- confint(fit)[2, ]\n```\n:::\n\n\n## 5. Concluding statement\n\n> Among Adelie penguins (*n* = 151), each additional mm of\n> bill length was associated with an increase of\n> 94 g in body mass (95% CI:\n> 71 to 118 g;\n> *p* = 3\\times 10^{-13}). Bill length explained\n> 30.1% of the variance in body\n> mass.\n\n::: {.notes}\nPoint out that R² below 30% is common and fine; the estimate is the\nstory, not the variance explained.\n:::\n\n## Common pitfalls\n\n- Extrapolating beyond the range of X.\n- Interpreting the intercept when X = 0 is nonsensical.\n- Quoting R² without reporting the slope and its interval.\n\n## Further reading\n\n- Faraway JJ. *Linear Models with R*, ch. 2.\n- Kutner MH et al. *Applied Linear Statistical Models*, ch. 1–3.\n- Weisberg S. *Applied Linear Regression*.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.2 (2025-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   \n[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    \n[5] LC_TIME=English_Germany.utf8    \n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] palmerpenguins_0.1.1 broom_1.0.12         lubridate_1.9.5     \n [4] forcats_1.0.1        stringr_1.6.0        dplyr_1.2.0         \n [7] purrr_1.2.2          readr_2.2.0          tidyr_1.3.2         \n[10] tibble_3.3.1         ggplot2_4.0.3        tidyverse_2.0.0     \n\nloaded via a namespace (and not attached):\n [1] Matrix_1.7-5       gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.2    \n [5] tidyselect_1.2.1   splines_4.5.2      scales_1.4.0       yaml_2.3.12       \n [9] fastmap_1.2.0      lattice_0.22-9     R6_2.6.1           labeling_0.4.3    \n[13] generics_0.1.4     knitr_1.51         backports_1.5.1    htmlwidgets_1.6.4 \n[17] pillar_1.11.1      RColorBrewer_1.1-3 tzdb_0.5.0         rlang_1.2.0       \n[21] utf8_1.2.6         stringi_1.8.7      xfun_0.57          S7_0.2.2          \n[25] otel_0.2.0         timechange_0.4.0   cli_3.6.6          mgcv_1.9-4        \n[29] withr_3.0.2        magrittr_2.0.4     digest_0.6.39      grid_4.5.2        \n[33] hms_1.1.4          nlme_3.1-169       lifecycle_1.0.5    vctrs_0.7.3       \n[37] evaluate_1.0.5     glue_1.8.0         farver_2.1.2       rmarkdown_2.31    \n[41] tools_4.5.2        pkgconfig_2.0.3    htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "lab_week1_session2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}